import type { AssistantRecommendationCatalogEntry } from "@/types/assistant-recommendation";

export const ASSISTANT_RECOMMENDATION_CATALOG: AssistantRecommendationCatalogEntry[] = [
  // HOME + MOTION — action presets
  {
    id: "goal_celebration",
    category: "trending",
    pages: ["home", "motion", "library"],
    emoji: "⚽",
    titleKey: "assistant.recommendation.goalCelebration.title",
    descriptionKey: "assistant.recommendation.goalCelebration.description",
    whyKey: "assistant.recommendation.goalCelebration.why",
    statusReadyKey: "assistant.recommendation.goalCelebration.statusReady",
    statusMissingKey: "assistant.recommendation.goalCelebration.statusMissing",
    promptMessage: "Ik wil een filmpje waarin ik een doelpunt maak",
    actionPresetId: "goal_celebration",
    requiresCharacter: true,
    trendingScore: 100,
  },
  {
    id: "red_carpet_moment",
    category: "trending",
    pages: ["home", "motion"],
    emoji: "🎬",
    titleKey: "assistant.recommendation.redCarpet.title",
    descriptionKey: "assistant.recommendation.redCarpet.description",
    whyKey: "assistant.recommendation.redCarpet.why",
    statusReadyKey: "assistant.recommendation.redCarpet.statusReady",
    promptMessage: "Ik wil over een rode loper lopen als filmster",
    actionPresetId: "red_carpet_moment",
    requiresCharacter: true,
    trendingScore: 95,
  },
  {
    id: "championship_celebration",
    category: "trending",
    pages: ["home", "motion"],
    emoji: "🏆",
    titleKey: "assistant.recommendation.championship.title",
    descriptionKey: "assistant.recommendation.championship.description",
    whyKey: "assistant.recommendation.championship.why",
    promptMessage: "Ik wil een kampioenschap vieren in een video",
    actionPresetId: "championship_celebration",
    requiresCharacter: true,
    trendingScore: 90,
  },
  {
    id: "snowboard_jump",
    category: "trending",
    pages: ["home", "motion", "library"],
    emoji: "🏂",
    titleKey: "assistant.recommendation.snowboardJump.title",
    descriptionKey: "assistant.recommendation.snowboardJump.description",
    whyKey: "assistant.recommendation.snowboardJump.why",
    statusReadyKey: "assistant.recommendation.snowboardJump.statusReady",
    promptMessage: "Ik wil mezelf op een snowboard zien met een sprong",
    actionPresetId: "snowboard_jump",
    requiresCharacter: true,
    requiresMotionReady: true,
    trendingScore: 88,
  },
  {
    id: "moonwalk",
    category: "for_you",
    pages: ["home", "motion"],
    emoji: "🕺",
    titleKey: "assistant.recommendation.moonwalk.title",
    descriptionKey: "assistant.recommendation.moonwalk.description",
    whyKey: "assistant.recommendation.moonwalk.why",
    promptMessage: "Ik wil een moonwalk doen in een video",
    actionPresetId: "moonwalk",
    requiresCharacter: true,
    trendingScore: 85,
  },
  {
    id: "sports_car_arrival",
    category: "for_you",
    pages: ["home", "motion"],
    emoji: "🚗",
    titleKey: "assistant.recommendation.sportsCar.title",
    descriptionKey: "assistant.recommendation.sportsCar.description",
    whyKey: "assistant.recommendation.sportsCar.why",
    promptMessage: "Ik wil aan komen rijden in een sportwagen alsof ik beroemd ben",
    actionPresetId: "sports_car_arrival",
    requiresCharacter: true,
    trendingScore: 84,
  },
  {
    id: "stage_performance",
    category: "for_you",
    pages: ["home", "motion"],
    emoji: "🎤",
    titleKey: "assistant.recommendation.concertStage.title",
    descriptionKey: "assistant.recommendation.concertStage.description",
    whyKey: "assistant.recommendation.concertStage.why",
    promptMessage: "Ik wil op een concertpodium staan voor duizenden fans",
    actionPresetId: "stage_performance",
    requiresCharacter: true,
    trendingScore: 83,
  },
  {
    id: "fans_recognize_me",
    category: "for_you",
    pages: ["home", "motion"],
    emoji: "📣",
    titleKey: "assistant.recommendation.fansRecognize.title",
    descriptionKey: "assistant.recommendation.fansRecognize.description",
    whyKey: "assistant.recommendation.fansRecognize.why",
    promptMessage: "Ik wil een filmpje maken waarin mensen mijn naam roepen",
    actionPresetId: "fans_recognize_me",
    requiresCharacter: true,
    trendingScore: 82,
  },
  {
    id: "basketball_dunk",
    category: "trending",
    pages: ["motion"],
    emoji: "🏀",
    titleKey: "assistant.recommendation.basketballDunk.title",
    descriptionKey: "assistant.recommendation.basketballDunk.description",
    whyKey: "assistant.recommendation.basketballDunk.why",
    promptMessage: "Ik wil een dunk maken en vieren in een video",
    actionPresetId: "basketball_dunk_celebration",
    requiresCharacter: true,
    trendingScore: 80,
  },
  {
    id: "skateboard_trick",
    category: "quick_starts",
    pages: ["motion"],
    emoji: "🛹",
    titleKey: "assistant.recommendation.skateboardTrick.title",
    descriptionKey: "assistant.recommendation.skateboardTrick.description",
    whyKey: "assistant.recommendation.skateboardTrick.why",
    promptMessage: "Ik wil een skateboard trick doen in een video",
    actionPresetId: "skateboard_trick",
    requiresCharacter: true,
    trendingScore: 78,
  },
  {
    id: "stadium_entrance",
    category: "quick_starts",
    pages: ["motion"],
    emoji: "🏟",
    titleKey: "assistant.recommendation.stadiumWalkout.title",
    descriptionKey: "assistant.recommendation.stadiumWalkout.description",
    whyKey: "assistant.recommendation.stadiumWalkout.why",
    promptMessage: "Ik wil het stadion binnenlopen met zelfvertrouwen",
    actionPresetId: "stadium_entrance",
    requiresCharacter: true,
    trendingScore: 77,
  },
  {
    id: "mountain_summit",
    category: "quick_starts",
    pages: ["motion"],
    emoji: "⛰",
    titleKey: "assistant.recommendation.mountainSummit.title",
    descriptionKey: "assistant.recommendation.mountainSummit.description",
    whyKey: "assistant.recommendation.mountainSummit.why",
    promptMessage: "Ik wil op een bergtop staan in een epische video",
    actionPresetId: "mountain_summit",
    requiresCharacter: true,
    trendingScore: 76,
  },
  // EDITOR — fusion as outcomes
  {
    id: "outfit_on_self",
    category: "for_you",
    pages: ["home", "editor", "library"],
    emoji: "🎽",
    titleKey: "assistant.recommendation.outfitOnSelf.title",
    descriptionKey: "assistant.recommendation.outfitOnSelf.description",
    whyKey: "assistant.recommendation.outfitOnSelf.why",
    promptMessage: "Zet een nieuwe outfit op mij",
    fusionIntent: "outfit_from_reference",
    requiresCharacter: true,
    trendingScore: 92,
  },
  {
    id: "movie_poster",
    category: "for_you",
    pages: ["editor", "library"],
    emoji: "🎬",
    titleKey: "assistant.recommendation.moviePoster.title",
    descriptionKey: "assistant.recommendation.moviePoster.description",
    whyKey: "assistant.recommendation.moviePoster.why",
    promptMessage: "Maak een bioscoopposter van mij",
    fusionIntent: "poster_social_composite",
    requiresCharacter: true,
    trendingScore: 86,
  },
  {
    id: "future_age_70",
    category: "hidden_possibilities",
    pages: ["home", "editor"],
    emoji: "🧓",
    titleKey: "assistant.recommendation.futureAge70.title",
    descriptionKey: "assistant.recommendation.futureAge70.description",
    whyKey: "assistant.recommendation.futureAge70.why",
    promptMessage: "Ik wil zien hoe ik eruit zie op mijn 70e",
    fusionIntent: "future_look",
    requiresCharacter: true,
    hiddenFeature: true,
    trendingScore: 94,
  },
  {
    id: "future_child",
    category: "hidden_possibilities",
    pages: ["home", "editor"],
    emoji: "👶",
    titleKey: "assistant.recommendation.futureChild.title",
    descriptionKey: "assistant.recommendation.futureChild.description",
    whyKey: "assistant.recommendation.futureChild.why",
    statusReadyKey: "assistant.recommendation.futureChild.statusReady",
    promptMessage: "Ik wil zien hoe ons toekomstige kind eruit kan zien",
    fusionIntent: "future_child",
    requiresFamilyPhotos: true,
    hiddenFeature: true,
    trendingScore: 96,
  },
  {
    id: "genetic_blend",
    category: "hidden_possibilities",
    pages: ["editor"],
    emoji: "🧬",
    titleKey: "assistant.recommendation.geneticBlend.title",
    descriptionKey: "assistant.recommendation.geneticBlend.description",
    whyKey: "assistant.recommendation.geneticBlend.why",
    promptMessage: "Vergelijk familiekenmerken in één beeld",
    fusionIntent: "genetic_blend",
    requiresFamilyPhotos: true,
    hiddenFeature: true,
    trendingScore: 75,
  },
  {
    id: "fantasy_creature",
    category: "hidden_possibilities",
    pages: ["home", "editor"],
    emoji: "🐶",
    titleKey: "assistant.recommendation.fantasyCreature.title",
    descriptionKey: "assistant.recommendation.fantasyCreature.description",
    whyKey: "assistant.recommendation.fantasyCreature.why",
    promptMessage: "Maak een fantasiedier van mij",
    fusionIntent: "fantasy_creature",
    hiddenFeature: true,
    trendingScore: 74,
  },
  {
    id: "mascot_transform",
    category: "hidden_possibilities",
    pages: ["home", "studio", "editor"],
    emoji: "🎭",
    titleKey: "assistant.recommendation.mascotTransform.title",
    descriptionKey: "assistant.recommendation.mascotTransform.description",
    whyKey: "assistant.recommendation.mascotTransform.why",
    promptMessage: "Verander mezelf in een mascotte",
    fusionIntent: "mascot_into_human",
    hiddenFeature: true,
    trendingScore: 87,
  },
  {
    id: "brand_on_product",
    category: "hidden_possibilities",
    pages: ["editor"],
    emoji: "🏷",
    titleKey: "assistant.recommendation.brandOnProduct.title",
    descriptionKey: "assistant.recommendation.brandOnProduct.description",
    whyKey: "assistant.recommendation.brandOnProduct.why",
    promptMessage: "Voeg mijn merk toe aan een product",
    fusionIntent: "product_logo_placement",
    hiddenFeature: true,
    trendingScore: 70,
  },
  {
    id: "combine_characters",
    category: "hidden_possibilities",
    pages: ["editor"],
    emoji: "👥",
    titleKey: "assistant.recommendation.combineCharacters.title",
    descriptionKey: "assistant.recommendation.combineCharacters.description",
    whyKey: "assistant.recommendation.combineCharacters.why",
    promptMessage: "Combineer twee personages in één scene",
    fusionIntent: "multi_character_scene",
    hiddenFeature: true,
    trendingScore: 68,
  },
  // STUDIO
  {
    id: "new_character",
    category: "quick_starts",
    pages: ["home", "studio"],
    emoji: "👨‍🍳",
    titleKey: "assistant.recommendation.newCharacter.title",
    descriptionKey: "assistant.recommendation.newCharacter.description",
    whyKey: "assistant.recommendation.newCharacter.why",
    promptMessage: "Ik wil een nieuw personage maken",
    trendingScore: 72,
  },
  {
    id: "start_story",
    category: "for_you",
    pages: ["studio"],
    emoji: "📖",
    titleKey: "assistant.recommendation.startStory.title",
    descriptionKey: "assistant.recommendation.startStory.description",
    whyKey: "assistant.recommendation.startStory.why",
    promptMessage: "Ik wil een verhaal starten voor mijn project",
    trendingScore: 71,
  },
  {
    id: "promo_video",
    category: "for_you",
    pages: ["studio", "home"],
    emoji: "🎬",
    titleKey: "assistant.recommendation.promoVideo.title",
    descriptionKey: "assistant.recommendation.promoVideo.description",
    whyKey: "assistant.recommendation.promoVideo.why",
    promptMessage: "Ik wil een promotievideo maken",
    trendingScore: 73,
  },
  // PROJECTS
  {
    id: "continue_project",
    category: "continue_working",
    pages: ["home", "projects", "studio"],
    emoji: "▶",
    titleKey: "assistant.recommendation.continueProject.title",
    descriptionKey: "assistant.recommendation.continueProject.description",
    whyKey: "assistant.recommendation.continueProject.why",
    promptMessage: "Ga verder met mijn laatste project",
    trendingScore: 110,
  },
  {
    id: "add_voiceover",
    category: "continue_working",
    pages: ["projects", "publish", "studio"],
    emoji: "🎤",
    titleKey: "assistant.recommendation.addVoiceover.title",
    descriptionKey: "assistant.recommendation.addVoiceover.description",
    whyKey: "assistant.recommendation.addVoiceover.why",
    promptMessage: "Voeg een professionele voice-over toe aan mijn project",
    trendingScore: 65,
  },
  {
    id: "add_music",
    category: "continue_working",
    pages: ["projects", "publish", "studio"],
    emoji: "🎵",
    titleKey: "assistant.recommendation.addMusic.title",
    descriptionKey: "assistant.recommendation.addMusic.description",
    whyKey: "assistant.recommendation.addMusic.why",
    promptMessage: "Voeg achtergrondmuziek toe aan mijn project",
    trendingScore: 64,
  },
  {
    id: "make_export",
    category: "continue_working",
    pages: ["projects", "publish"],
    emoji: "📤",
    titleKey: "assistant.recommendation.makeExport.title",
    descriptionKey: "assistant.recommendation.makeExport.description",
    whyKey: "assistant.recommendation.makeExport.why",
    promptMessage: "Maak een export van mijn project",
    trendingScore: 63,
  },
  // PUBLISH
  {
    id: "tiktok_version",
    category: "for_you",
    pages: ["publish"],
    emoji: "📱",
    titleKey: "assistant.recommendation.tiktokVersion.title",
    descriptionKey: "assistant.recommendation.tiktokVersion.description",
    whyKey: "assistant.recommendation.tiktokVersion.why",
    promptMessage: "Maak een TikTok-versie van deze video",
    trendingScore: 82,
  },
  {
    id: "youtube_shorts",
    category: "for_you",
    pages: ["publish"],
    emoji: "🎬",
    titleKey: "assistant.recommendation.youtubeShorts.title",
    descriptionKey: "assistant.recommendation.youtubeShorts.description",
    whyKey: "assistant.recommendation.youtubeShorts.why",
    promptMessage: "Maak een YouTube Shorts versie van mijn video",
    trendingScore: 81,
  },
  {
    id: "add_subtitles",
    category: "for_you",
    pages: ["publish"],
    emoji: "📝",
    titleKey: "assistant.recommendation.addSubtitles.title",
    descriptionKey: "assistant.recommendation.addSubtitles.description",
    whyKey: "assistant.recommendation.addSubtitles.why",
    promptMessage: "Voeg automatische ondertitels toe",
    trendingScore: 79,
  },
  {
    id: "second_language",
    category: "hidden_possibilities",
    pages: ["publish"],
    emoji: "🌍",
    titleKey: "assistant.recommendation.secondLanguage.title",
    descriptionKey: "assistant.recommendation.secondLanguage.description",
    whyKey: "assistant.recommendation.secondLanguage.why",
    promptMessage: "Maak een tweede taalversie van mijn video",
    trendingScore: 78,
  },
  // USAGE
  {
    id: "reuse_assets",
    category: "for_you",
    pages: ["usage", "home"],
    emoji: "♻",
    titleKey: "assistant.recommendation.reuseAssets.title",
    descriptionKey: "assistant.recommendation.reuseAssets.description",
    whyKey: "assistant.recommendation.reuseAssets.why",
    promptMessage: "Hoe kan ik bestaande assets opnieuw gebruiken om credits te besparen?",
    trendingScore: 70,
  },
  {
    id: "unused_assets",
    category: "for_you",
    pages: ["usage"],
    emoji: "📦",
    titleKey: "assistant.recommendation.unusedAssets.title",
    descriptionKey: "assistant.recommendation.unusedAssets.description",
    whyKey: "assistant.recommendation.unusedAssets.why",
    promptMessage: "Welke assets heb ik nog niet gebruikt?",
    trendingScore: 69,
  },
  {
    id: "motion_ready_available",
    category: "for_you",
    pages: ["usage", "library", "motion"],
    emoji: "🎬",
    titleKey: "assistant.recommendation.motionReadyAvailable.title",
    descriptionKey: "assistant.recommendation.motionReadyAvailable.description",
    whyKey: "assistant.recommendation.motionReadyAvailable.why",
    statusReadyKey: "assistant.recommendation.motionReadyAvailable.statusReady",
    promptMessage: "Ik wil direct een nieuwe animatie starten met mijn motion-ready personage",
    requiresMotionReady: true,
    trendingScore: 91,
  },
  // LIBRARY — asset-specific (template, resolved in engine)
  {
    id: "library_goal_with_character",
    category: "for_you",
    pages: ["library"],
    emoji: "⚽",
    titleKey: "assistant.recommendation.libraryGoalCharacter.title",
    descriptionKey: "assistant.recommendation.libraryGoalCharacter.description",
    whyKey: "assistant.recommendation.libraryGoalCharacter.why",
    promptMessage: "Gebruik mijn personage voor een doelpuntvideo",
    actionPresetId: "goal_celebration",
    requiresCharacter: true,
    trendingScore: 93,
  },
  {
    id: "library_outfit_variant",
    category: "for_you",
    pages: ["library"],
    emoji: "🎽",
    titleKey: "assistant.recommendation.libraryOutfitVariant.title",
    descriptionKey: "assistant.recommendation.libraryOutfitVariant.description",
    whyKey: "assistant.recommendation.libraryOutfitVariant.why",
    promptMessage: "Maak een outfitvariant van dit personage",
    fusionIntent: "outfit_from_reference",
    requiresCharacter: true,
    trendingScore: 72,
  },
  {
    id: "film_trailer",
    category: "trending",
    pages: ["home"],
    emoji: "🎥",
    titleKey: "assistant.recommendation.filmTrailer.title",
    descriptionKey: "assistant.recommendation.filmTrailer.description",
    whyKey: "assistant.recommendation.filmTrailer.why",
    promptMessage: "Maak mijn eigen filmtrailer",
    trendingScore: 86,
  },
];
