/**
 * Central Assistant V4 tool capability registry.
 */

import { buildAssistantActionRoute } from "@/lib/assistant-route-builder";
import { buildEditorMorphActionRoute } from "@/lib/editor-morph-actions";
import type { AssistantToolCapability } from "@/types/assistant-v4";

function editorRoute(workflow: string, extra?: Record<string, string>): string {
  const params = new URLSearchParams({ workflow, ...extra });
  return `/editor?${params.toString()}`;
}

function morphTool(
  id: import("@/lib/editor-morph-actions").EditorMorphActionId,
  partial: Omit<AssistantToolCapability, "toolId" | "route" | "morphActionId" | "category">
): AssistantToolCapability {
  return {
    toolId: id,
    category: "morph",
    route: buildEditorMorphActionRoute(id),
    morphActionId: id,
    ...partial,
  };
}

export const ASSISTANT_TOOL_CAPABILITIES: AssistantToolCapability[] = [
  // —— Editor tools ——
  {
    toolId: "editor_image_edit",
    displayNameNl: "Beeldbewerking",
    displayNameEn: "Image edit",
    category: "editor",
    supportedAssetTypes: ["image", "mascot", "human", "animal", "character", "product"],
    supportedPartTypes: ["*"],
    supportedActions: ["adjust", "refine", "enhance"],
    requiredInputs: ["asset"],
    optionalInputs: ["prompt"],
    defaultSettings: { workflow: "edit" },
    creditActionType: "image_generation",
    outputType: "image",
    route: editorRoute("edit"),
    safetyRules: ["preserve_identity_when_requested"],
    preserveOptions: ["background", "pose"],
  },
  {
    toolId: "editor_masked_edit",
    displayNameNl: "Gemaskerde bewerking",
    displayNameEn: "Masked edit",
    category: "editor",
    supportedAssetTypes: ["mascot", "human", "animal", "character"],
    supportedPartTypes: ["eyes", "mouth", "face", "hair", "outfit", "coat", "globe"],
    supportedActions: ["enlarge", "shrink", "color", "adjust", "refine"],
    requiredInputs: ["asset", "targetPart"],
    optionalInputs: ["operation", "prompt"],
    defaultSettings: { workflow: "edit", mode: "masked" },
    creditActionType: "image_generation",
    outputType: "image",
    route: editorRoute("edit", { mode: "masked" }),
    safetyRules: ["part_scoped_only", "preserve_unselected_parts"],
    preserveOptions: ["outfit", "globe", "pose", "background", "identity"],
  },
  {
    toolId: "editor_object_replace",
    displayNameNl: "Object vervangen",
    displayNameEn: "Object replacement",
    category: "editor",
    supportedAssetTypes: ["image", "mascot", "human", "animal", "prop"],
    supportedPartTypes: ["*"],
    supportedActions: ["replace"],
    requiredInputs: ["asset", "targetPart"],
    optionalInputs: ["replacementPrompt"],
    defaultSettings: { workflow: "edit", mode: "replace" },
    creditActionType: "image_generation",
    outputType: "image",
    route: editorRoute("edit", { mode: "replace" }),
    safetyRules: ["confirm_before_execute"],
    preserveOptions: ["background", "lighting"],
  },
  {
    toolId: "editor_background_edit",
    displayNameNl: "Achtergrond bewerken",
    displayNameEn: "Background edit",
    category: "editor",
    supportedAssetTypes: ["image", "mascot", "human", "animal", "product"],
    supportedPartTypes: ["background"],
    supportedActions: ["replace", "blur", "extend"],
    requiredInputs: ["asset"],
    optionalInputs: ["backgroundPrompt"],
    defaultSettings: { workflow: "edit", target: "background" },
    creditActionType: "image_generation",
    outputType: "image",
    route: editorRoute("edit", { target: "background" }),
    safetyRules: ["preserve_subject"],
    preserveOptions: ["subject", "identity", "outfit"],
  },
  {
    toolId: "editor_style_morph",
    displayNameNl: "Stijl morph",
    displayNameEn: "Style morph",
    category: "editor",
    supportedAssetTypes: ["mascot", "human", "animal"],
    supportedPartTypes: ["*"],
    supportedActions: ["cartoon", "cinematic", "stylize"],
    requiredInputs: ["asset"],
    optionalInputs: ["style"],
    defaultSettings: { workflow: "edit" },
    creditActionType: "image_generation",
    outputType: "image",
    route: editorRoute("edit"),
    safetyRules: ["preserve_identity"],
    preserveOptions: ["identity", "pose", "outfit"],
  },
  {
    toolId: "editor_color_edit",
    displayNameNl: "Kleur bewerken",
    displayNameEn: "Color edit",
    category: "editor",
    supportedAssetTypes: ["mascot", "human", "animal"],
    supportedPartTypes: ["eyes", "mouth", "hair", "outfit", "coat", "globe"],
    supportedActions: ["color", "recolor"],
    requiredInputs: ["asset", "targetPart"],
    optionalInputs: ["color"],
    defaultSettings: { workflow: "edit", operation: "color" },
    creditActionType: "image_generation",
    outputType: "image",
    route: editorRoute("edit", { operation: "color" }),
    safetyRules: ["part_scoped_only"],
    preserveOptions: ["identity", "pose", "outfit", "globe"],
  },
  {
    toolId: "editor_outfit_change",
    displayNameNl: "Outfit wijzigen",
    displayNameEn: "Outfit change",
    category: "editor",
    supportedAssetTypes: ["mascot", "human", "character"],
    supportedPartTypes: ["outfit", "clothing"],
    supportedActions: ["outfit", "business", "casual", "chef"],
    requiredInputs: ["asset"],
    optionalInputs: ["outfitStyle"],
    defaultSettings: { workflow: "edit", preserveIdentity: true, preserveFace: true },
    creditActionType: "image_generation",
    outputType: "image",
    route: buildEditorMorphActionRoute("outfit_change"),
    morphActionId: "outfit_change",
    safetyRules: ["preserve_identity", "preserve_face"],
    preserveOptions: ["identity", "face", "background", "pose"],
  },
  {
    toolId: "editor_expression_change",
    displayNameNl: "Expressie wijzigen",
    displayNameEn: "Expression change",
    category: "editor",
    supportedAssetTypes: ["mascot", "human", "animal"],
    supportedPartTypes: ["expression", "mouth", "face"],
    supportedActions: ["happy", "serious", "friendlier", "vrolijker"],
    requiredInputs: ["asset"],
    optionalInputs: ["expression"],
    defaultSettings: { workflow: "edit", targetPart: "expression" },
    creditActionType: "image_generation",
    outputType: "image",
    route: buildEditorMorphActionRoute("expression_change"),
    morphActionId: "expression_change",
    safetyRules: ["preserve_identity"],
    preserveOptions: ["outfit", "pose", "globe", "background"],
  },
  {
    toolId: "editor_pose_change",
    displayNameNl: "Pose wijzigen",
    displayNameEn: "Pose change",
    category: "editor",
    supportedAssetTypes: ["mascot", "human", "animal"],
    supportedPartTypes: ["pose"],
    supportedActions: ["pose"],
    requiredInputs: ["asset"],
    optionalInputs: ["pose"],
    defaultSettings: { workflow: "edit", targetPart: "pose" },
    creditActionType: "image_generation",
    outputType: "image",
    route: buildEditorMorphActionRoute("pose_change"),
    morphActionId: "pose_change",
    safetyRules: ["preserve_identity"],
    preserveOptions: ["face", "outfit", "background"],
  },
  {
    toolId: "editor_prop_replace",
    displayNameNl: "Prop vervangen",
    displayNameEn: "Prop replace",
    category: "editor",
    supportedAssetTypes: ["image", "prop", "product"],
    supportedPartTypes: ["prop"],
    supportedActions: ["replace"],
    requiredInputs: ["asset"],
    optionalInputs: ["propPrompt"],
    defaultSettings: { workflow: "edit", target: "prop" },
    creditActionType: "image_generation",
    outputType: "image",
    route: editorRoute("edit", { target: "prop" }),
    safetyRules: [],
    preserveOptions: ["background", "character"],
  },
  {
    toolId: "editor_remove_object",
    displayNameNl: "Object verwijderen",
    displayNameEn: "Remove object",
    category: "editor",
    supportedAssetTypes: ["image", "mascot", "human", "animal"],
    supportedPartTypes: ["*"],
    supportedActions: ["remove"],
    requiredInputs: ["asset", "targetPart"],
    optionalInputs: [],
    defaultSettings: { workflow: "edit", mode: "remove" },
    creditActionType: "image_generation",
    outputType: "image",
    route: editorRoute("edit", { mode: "remove" }),
    safetyRules: ["confirm_before_execute"],
    preserveOptions: ["background"],
    isFreeLocal: true,
  },
  {
    toolId: "editor_add_object",
    displayNameNl: "Object toevoegen",
    displayNameEn: "Add object",
    category: "editor",
    supportedAssetTypes: ["image", "mascot", "human", "animal"],
    supportedPartTypes: ["*"],
    supportedActions: ["add"],
    requiredInputs: ["asset", "objectPrompt"],
    optionalInputs: ["placement"],
    defaultSettings: { workflow: "edit", mode: "add" },
    creditActionType: "image_generation",
    outputType: "image",
    route: editorRoute("edit", { mode: "add" }),
    safetyRules: [],
    preserveOptions: ["existing_subject"],
  },

  // —— Morph tools ——
  morphTool("human_to_cartoon", {
    displayNameNl: "Mens naar cartoon",
    displayNameEn: "Human to cartoon",
    supportedAssetTypes: ["human"],
    supportedPartTypes: ["*"],
    supportedActions: ["cartoon"],
    requiredInputs: ["asset"],
    optionalInputs: ["style"],
    defaultSettings: { preserveIdentity: true, preserveFace: true },
    creditActionType: "image_generation",
    outputType: "image",
    safetyRules: ["preserve_identity", "block_sensitive_traits"],
    preserveOptions: ["identity", "face", "background"],
    blockedTraits: ["ethnicity_change", "age_change", "skin_tone_change"],
  }),
  morphTool("human_to_mascot", {
    displayNameNl: "Mens naar mascotte",
    displayNameEn: "Human to mascot",
    supportedAssetTypes: ["human"],
    supportedPartTypes: ["*"],
    supportedActions: ["mascot"],
    requiredInputs: ["asset"],
    optionalInputs: ["style"],
    defaultSettings: { preserveIdentity: true },
    creditActionType: "image_generation",
    outputType: "image",
    safetyRules: ["preserve_identity", "block_sensitive_traits"],
    preserveOptions: ["identity", "recognizable_features"],
    blockedTraits: ["ethnicity_change", "age_change"],
  }),
  morphTool("portrait_to_avatar", {
    displayNameNl: "Portret naar avatar",
    displayNameEn: "Portrait to avatar",
    supportedAssetTypes: ["human"],
    supportedPartTypes: ["face"],
    supportedActions: ["avatar"],
    requiredInputs: ["asset"],
    optionalInputs: [],
    defaultSettings: { preserveIdentity: true },
    creditActionType: "image_generation",
    outputType: "image",
    safetyRules: ["preserve_identity"],
    preserveOptions: ["identity", "face_shape"],
    blockedTraits: ["ethnicity_change"],
  }),
  morphTool("pet_to_cartoon", {
    displayNameNl: "Huisdier naar cartoon",
    displayNameEn: "Pet to cartoon",
    supportedAssetTypes: ["animal"],
    supportedPartTypes: ["*"],
    supportedActions: ["cartoon"],
    requiredInputs: ["asset"],
    optionalInputs: [],
    defaultSettings: { preserveBreedShape: true, preserveFurPattern: true },
    creditActionType: "image_generation",
    outputType: "image",
    safetyRules: ["preserve_breed"],
    preserveOptions: ["breed_shape", "fur_pattern", "eye_color"],
  }),
  morphTool("pet_to_mascot", {
    displayNameNl: "Huisdier naar mascotte",
    displayNameEn: "Pet to mascot",
    supportedAssetTypes: ["animal"],
    supportedPartTypes: ["*"],
    supportedActions: ["mascot"],
    requiredInputs: ["asset"],
    optionalInputs: ["style"],
    defaultSettings: {
      preserveBreedShape: true,
      preserveFurPattern: true,
      preserveEyeColor: true,
      style: "friendly_mascot",
    },
    creditActionType: "image_generation",
    outputType: "image",
    safetyRules: ["preserve_breed"],
    preserveOptions: ["breed_shape", "fur_pattern", "eye_color", "tail"],
  }),
  morphTool("animal_to_fantasy_creature", {
    displayNameNl: "Dier naar fantasy",
    displayNameEn: "Animal to fantasy creature",
    supportedAssetTypes: ["animal"],
    supportedPartTypes: ["*"],
    supportedActions: ["fantasy"],
    requiredInputs: ["asset"],
    optionalInputs: [],
    defaultSettings: { preserveBreedShape: true },
    creditActionType: "image_generation",
    outputType: "image",
    safetyRules: [],
    preserveOptions: ["silhouette"],
  }),
  morphTool("mascot_style_morph", {
    displayNameNl: "Mascotte stijl morph",
    displayNameEn: "Mascot style morph",
    supportedAssetTypes: ["mascot", "character"],
    supportedPartTypes: ["*"],
    supportedActions: ["cartoon", "cinematic", "stylize"],
    requiredInputs: ["asset"],
    optionalInputs: ["style"],
    defaultSettings: { preserveGlobe: true, preserveOutfit: true },
    creditActionType: "image_generation",
    outputType: "image",
    safetyRules: ["preserve_brand_elements"],
    preserveOptions: ["globe", "outfit", "pose", "background"],
  }),
  morphTool("mascot_pose_morph", {
    displayNameNl: "Mascotte pose morph",
    displayNameEn: "Mascot pose morph",
    supportedAssetTypes: ["mascot", "character"],
    supportedPartTypes: ["pose"],
    supportedActions: ["pose"],
    requiredInputs: ["asset"],
    optionalInputs: ["pose"],
    defaultSettings: { preserveGlobe: true, preserveOutfit: true, preserveExpression: true },
    creditActionType: "image_generation",
    outputType: "image",
    safetyRules: [],
    preserveOptions: ["globe", "outfit", "expression", "face"],
  }),
  morphTool("mascot_expression_morph", {
    displayNameNl: "Mascotte expressie morph",
    displayNameEn: "Mascot expression morph",
    supportedAssetTypes: ["mascot", "character"],
    supportedPartTypes: ["expression", "mouth", "face"],
    supportedActions: ["happy", "vrolijker", "serious", "friendlier"],
    requiredInputs: ["asset"],
    optionalInputs: ["expression"],
    defaultSettings: {
      targetPart: "expression",
      preserveGlobe: true,
      preserveOutfit: true,
      preservePose: true,
    },
    creditActionType: "image_generation",
    outputType: "image",
    safetyRules: ["preserve_brand_elements"],
    preserveOptions: ["globe", "outfit", "pose", "background"],
  }),
  morphTool("mascot_variant_morph", {
    displayNameNl: "Mascotte variant",
    displayNameEn: "Mascot variant",
    supportedAssetTypes: ["mascot", "character"],
    supportedPartTypes: ["outfit"],
    supportedActions: ["chef", "garden", "designer", "business", "casual"],
    requiredInputs: ["asset"],
    optionalInputs: ["variant"],
    defaultSettings: { preserveGlobe: true, preserveFace: true },
    creditActionType: "image_generation",
    outputType: "image",
    safetyRules: [],
    preserveOptions: ["globe", "face", "pose"],
  }),

  // —— Studio tools ——
  {
    toolId: "studio_storyboard_create",
    displayNameNl: "Storyboard maken",
    displayNameEn: "Create storyboard",
    category: "studio",
    supportedAssetTypes: ["image", "video", "character"],
    supportedPartTypes: [],
    supportedActions: ["create"],
    requiredInputs: ["project"],
    optionalInputs: ["preset"],
    defaultSettings: { preset: "default" },
    creditActionType: "storyboard_generation",
    outputType: "storyboard",
    route: "/studio/storyboards/new",
    safetyRules: [],
    preserveOptions: [],
  },
  {
    toolId: "studio_scene_generation",
    displayNameNl: "Scène genereren",
    displayNameEn: "Scene generation",
    category: "studio",
    supportedAssetTypes: ["character", "world", "location"],
    supportedPartTypes: [],
    supportedActions: ["generate"],
    requiredInputs: ["project"],
    optionalInputs: ["scenePrompt"],
    defaultSettings: {},
    creditActionType: "image_generation",
    outputType: "image",
    route: buildAssistantActionRoute("create_motion_video"),
    actionId: "create_motion_video",
    safetyRules: [],
    preserveOptions: ["characters", "world"],
  },
  {
    toolId: "studio_character_generation",
    displayNameNl: "Personage genereren",
    displayNameEn: "Character generation",
    category: "studio",
    supportedAssetTypes: ["character", "human", "mascot"],
    supportedPartTypes: [],
    supportedActions: ["create"],
    requiredInputs: [],
    optionalInputs: ["characterPrompt"],
    defaultSettings: {},
    creditActionType: "character_generation",
    outputType: "asset",
    route: buildAssistantActionRoute("create_character"),
    actionId: "create_character",
    safetyRules: [],
    preserveOptions: [],
  },
  {
    toolId: "studio_world_generation",
    displayNameNl: "Wereld genereren",
    displayNameEn: "World generation",
    category: "studio",
    supportedAssetTypes: ["world"],
    supportedPartTypes: [],
    supportedActions: ["create"],
    requiredInputs: [],
    optionalInputs: ["worldPrompt"],
    defaultSettings: {},
    creditActionType: "image_generation",
    outputType: "asset",
    route: "/studio/worlds/new",
    safetyRules: [],
    preserveOptions: [],
  },
  {
    toolId: "studio_location_generation",
    displayNameNl: "Locatie genereren",
    displayNameEn: "Location generation",
    category: "studio",
    supportedAssetTypes: ["location"],
    supportedPartTypes: [],
    supportedActions: ["create"],
    requiredInputs: [],
    optionalInputs: ["locationPrompt"],
    defaultSettings: {},
    creditActionType: "image_generation",
    outputType: "asset",
    route: buildAssistantActionRoute("prepare_location"),
    actionId: "prepare_location",
    safetyRules: [],
    preserveOptions: ["world"],
  },
  {
    toolId: "studio_prop_generation",
    displayNameNl: "Prop genereren",
    displayNameEn: "Prop generation",
    category: "studio",
    supportedAssetTypes: ["prop", "product"],
    supportedPartTypes: [],
    supportedActions: ["create"],
    requiredInputs: [],
    optionalInputs: ["propPrompt"],
    defaultSettings: {},
    creditActionType: "image_generation",
    outputType: "asset",
    route: buildAssistantActionRoute("prepare_prop"),
    actionId: "prepare_prop",
    safetyRules: [],
    preserveOptions: [],
  },

  // —— Motion tools ——
  {
    toolId: "motion_image_to_video",
    displayNameNl: "Afbeelding naar video",
    displayNameEn: "Image to video",
    category: "motion",
    supportedAssetTypes: ["image", "character"],
    supportedPartTypes: [],
    supportedActions: ["animate"],
    requiredInputs: ["asset"],
    optionalInputs: ["duration"],
    defaultSettings: { mode: "image_to_video", preserveCharacters: true },
    creditActionType: "motion_render",
    estimatedCredits: 450,
    outputType: "video",
    route: "/animate/instant?mode=image_to_video",
    safetyRules: ["confirm_before_execute"],
    preserveOptions: ["characters", "style"],
  },
  {
    toolId: "motion_story_render",
    displayNameNl: "Story render",
    displayNameEn: "Story render",
    category: "motion",
    supportedAssetTypes: ["video", "character"],
    supportedPartTypes: [],
    supportedActions: ["render"],
    requiredInputs: ["project"],
    optionalInputs: ["subtitles"],
    defaultSettings: { mode: "story", preserveCharacters: true, subtitles: "recommended" },
    creditActionType: "motion_render",
    estimatedCredits: 450,
    outputType: "video",
    route: buildAssistantActionRoute("create_motion_video"),
    actionId: "create_motion_video",
    safetyRules: ["confirm_before_execute"],
    preserveOptions: ["characters", "voice"],
  },
  {
    toolId: "motion_transition_render",
    displayNameNl: "Transitie render",
    displayNameEn: "Transition render",
    category: "motion",
    supportedAssetTypes: ["video"],
    supportedPartTypes: [],
    supportedActions: ["transition"],
    requiredInputs: ["project"],
    optionalInputs: [],
    defaultSettings: { mode: "transition" },
    creditActionType: "motion_render",
    outputType: "video",
    route: "/animate/instant?mode=transition",
    safetyRules: [],
    preserveOptions: [],
  },
  {
    toolId: "motion_segment_retry",
    displayNameNl: "Segment opnieuw",
    displayNameEn: "Segment retry",
    category: "motion",
    supportedAssetTypes: ["video"],
    supportedPartTypes: [],
    supportedActions: ["retry"],
    requiredInputs: ["segmentId"],
    optionalInputs: [],
    defaultSettings: { mode: "retry" },
    creditActionType: "motion_render",
    outputType: "video",
    route: "/animate/instant?mode=retry",
    safetyRules: [],
    preserveOptions: ["characters"],
  },
  {
    toolId: "motion_full_rerender",
    displayNameNl: "Volledige rerender",
    displayNameEn: "Full rerender",
    category: "motion",
    supportedAssetTypes: ["video"],
    supportedPartTypes: [],
    supportedActions: ["rerender"],
    requiredInputs: ["project"],
    optionalInputs: [],
    defaultSettings: { mode: "full_rerender" },
    creditActionType: "motion_render",
    estimatedCredits: 450,
    outputType: "video",
    route: "/animate/instant?mode=full_rerender",
    safetyRules: ["confirm_before_execute"],
    preserveOptions: [],
  },

  // —— Audio tools ——
  {
    toolId: "audio_voice_generation",
    displayNameNl: "Voice-over genereren",
    displayNameEn: "Voice-over generation",
    category: "audio",
    supportedAssetTypes: ["video", "character"],
    supportedPartTypes: [],
    supportedActions: ["voice"],
    requiredInputs: ["project", "script"],
    optionalInputs: ["voiceId", "language"],
    defaultSettings: {},
    creditActionType: "voice_generation",
    outputType: "audio",
    route: buildAssistantActionRoute("prepare_music"),
    actionId: "prepare_music",
    safetyRules: [],
    preserveOptions: [],
  },
  {
    toolId: "audio_voice_preview",
    displayNameNl: "Stem preview",
    displayNameEn: "Voice preview",
    category: "audio",
    supportedAssetTypes: ["character"],
    supportedPartTypes: [],
    supportedActions: ["preview"],
    requiredInputs: ["voiceId"],
    optionalInputs: ["sampleText"],
    defaultSettings: {},
    creditActionType: "voice_generation",
    outputType: "audio",
    route: "/studio/voice?mode=preview",
    safetyRules: [],
    preserveOptions: [],
    isFreeLocal: true,
  },
  {
    toolId: "audio_voice_clone",
    displayNameNl: "Stem klonen",
    displayNameEn: "Voice clone",
    category: "audio",
    supportedAssetTypes: ["character"],
    supportedPartTypes: [],
    supportedActions: ["clone"],
    requiredInputs: ["sampleAudio"],
    optionalInputs: [],
    defaultSettings: {},
    creditActionType: "voice_generation",
    outputType: "audio",
    route: "/studio/voice?mode=clone",
    safetyRules: ["confirm_before_execute"],
    preserveOptions: [],
  },
  {
    toolId: "audio_music_generation",
    displayNameNl: "Muziek genereren",
    displayNameEn: "Music generation",
    category: "audio",
    supportedAssetTypes: ["video"],
    supportedPartTypes: [],
    supportedActions: ["music"],
    requiredInputs: ["project"],
    optionalInputs: ["mood", "duration"],
    defaultSettings: {},
    creditActionType: "music_generation",
    outputType: "audio",
    route: buildAssistantActionRoute("prepare_music"),
    actionId: "prepare_music",
    safetyRules: [],
    preserveOptions: [],
  },
  {
    toolId: "audio_sfx_generation",
    displayNameNl: "Geluidseffect",
    displayNameEn: "Sound effect",
    category: "audio",
    supportedAssetTypes: ["video"],
    supportedPartTypes: [],
    supportedActions: ["sfx"],
    requiredInputs: ["project"],
    optionalInputs: ["sfxPrompt"],
    defaultSettings: {},
    creditActionType: "music_generation",
    outputType: "audio",
    route: buildAssistantActionRoute("prepare_sfx"),
    actionId: "prepare_sfx",
    safetyRules: [],
    preserveOptions: [],
  },
  {
    toolId: "audio_subtitles",
    displayNameNl: "Ondertitels",
    displayNameEn: "Subtitles",
    category: "audio",
    supportedAssetTypes: ["video"],
    supportedPartTypes: [],
    supportedActions: ["subtitles"],
    requiredInputs: ["project", "transcript"],
    optionalInputs: ["language"],
    defaultSettings: {},
    creditActionType: "voice_generation",
    outputType: "export",
    route: buildAssistantActionRoute("create_publish_export"),
    actionId: "create_publish_export",
    safetyRules: [],
    preserveOptions: ["timing"],
  },
  {
    toolId: "audio_translation",
    displayNameNl: "Vertaling",
    displayNameEn: "Translation",
    category: "audio",
    supportedAssetTypes: ["video"],
    supportedPartTypes: [],
    supportedActions: ["translate"],
    requiredInputs: ["project", "targetLanguage"],
    optionalInputs: [],
    defaultSettings: {},
    creditActionType: "voice_generation",
    outputType: "export",
    route: buildAssistantActionRoute("create_publish_export"),
    actionId: "create_publish_export",
    safetyRules: [],
    preserveOptions: ["voice", "timing"],
  },

  // —— Publish tools ——
  {
    toolId: "publish_photo_story",
    displayNameNl: "Photo story export",
    displayNameEn: "Photo story export",
    category: "publish",
    supportedAssetTypes: ["image", "video"],
    supportedPartTypes: [],
    supportedActions: ["export"],
    requiredInputs: ["project"],
    optionalInputs: [],
    defaultSettings: { format: "photo_story" },
    creditActionType: "export",
    outputType: "export",
    route: buildAssistantActionRoute("create_publish_export"),
    actionId: "create_publish_export",
    safetyRules: [],
    preserveOptions: [],
    isFreeLocal: true,
  },
  {
    toolId: "publish_slideshow",
    displayNameNl: "Slideshow export",
    displayNameEn: "Slideshow export",
    category: "publish",
    supportedAssetTypes: ["video", "image"],
    supportedPartTypes: [],
    supportedActions: ["export"],
    requiredInputs: ["project"],
    optionalInputs: [],
    defaultSettings: { format: "slideshow" },
    creditActionType: "export",
    outputType: "export",
    route: buildAssistantActionRoute("create_publish_export"),
    actionId: "create_publish_export",
    safetyRules: [],
    preserveOptions: [],
  },
  {
    toolId: "publish_mp4",
    displayNameNl: "MP4 export",
    displayNameEn: "MP4 export",
    category: "publish",
    supportedAssetTypes: ["video"],
    supportedPartTypes: [],
    supportedActions: ["export"],
    requiredInputs: ["project"],
    optionalInputs: [],
    defaultSettings: { format: "mp4" },
    creditActionType: "export",
    outputType: "export",
    route: buildAssistantActionRoute("create_publish_export"),
    actionId: "create_publish_export",
    safetyRules: [],
    preserveOptions: [],
  },
  {
    toolId: "publish_poster",
    displayNameNl: "Poster export",
    displayNameEn: "Poster export",
    category: "publish",
    supportedAssetTypes: ["image", "video"],
    supportedPartTypes: [],
    supportedActions: ["export"],
    requiredInputs: ["project"],
    optionalInputs: [],
    defaultSettings: { format: "poster" },
    creditActionType: "image_generation",
    outputType: "export",
    route: buildAssistantActionRoute("create_publish_export"),
    actionId: "create_publish_export",
    safetyRules: [],
    preserveOptions: [],
  },
  {
    toolId: "publish_language_export",
    displayNameNl: "Taal export",
    displayNameEn: "Language export",
    category: "publish",
    supportedAssetTypes: ["video"],
    supportedPartTypes: [],
    supportedActions: ["export", "translate"],
    requiredInputs: ["project", "language"],
    optionalInputs: [],
    defaultSettings: { format: "localized" },
    creditActionType: "export",
    outputType: "export",
    route: buildAssistantActionRoute("create_publish_export"),
    actionId: "create_publish_export",
    safetyRules: [],
    preserveOptions: [],
  },
];

const TOOL_BY_ID = new Map(ASSISTANT_TOOL_CAPABILITIES.map((t) => [t.toolId, t]));

export function getAssistantToolCapability(toolId: string): AssistantToolCapability | null {
  return TOOL_BY_ID.get(toolId) ?? null;
}

export function listAssistantToolsByCategory(category: AssistantToolCapability["category"]): AssistantToolCapability[] {
  return ASSISTANT_TOOL_CAPABILITIES.filter((t) => t.category === category);
}

export function listAssistantToolsForAsset(assetType: string): AssistantToolCapability[] {
  return ASSISTANT_TOOL_CAPABILITIES.filter(
    (t) =>
      t.supportedAssetTypes.includes(assetType as AssistantToolCapability["supportedAssetTypes"][number]) ||
      t.supportedAssetTypes.includes("image")
  );
}
