import type { Metadata } from "next";
import { HOMECHEFF_BRAND_ICON_ASSET_VERSION } from "@/lib/homecheff-brand-icon-version";

/** SSOT raster source — all favicon/touch assets are generated from this file. */
export const HOMECHEFF_BRAND_ICON_SOURCE = "/homecheff-globe-man.png" as const;

/**
 * Static public/ root paths — Safari fetches /favicon.ico before parsing HTML.
 * Generated by npm run generate:brand-icons (never hand-edit).
 */
export const HOMECHEFF_STATIC_ICON_PATHS = {
  faviconIco: "/favicon.ico",
  appleTouchIcon: "/apple-touch-icon.png",
} as const;

/** Versioned public assets for web manifest. */
export const HOMECHEFF_BRAND_ICON_PATHS = {
  source: HOMECHEFF_BRAND_ICON_SOURCE,
  favicon16: `/homecheff-favicon-16-${HOMECHEFF_BRAND_ICON_ASSET_VERSION}.png`,
  favicon32: `/homecheff-favicon-32-${HOMECHEFF_BRAND_ICON_ASSET_VERSION}.png`,
  appleTouchIcon: `/homecheff-apple-touch-icon-${HOMECHEFF_BRAND_ICON_ASSET_VERSION}.png`,
  webManifest: "/site.webmanifest",
} as const;

export const HOMECHEFF_BRAND_ICON_ALT = "HomeCheff";

/** Primary tab icon — Safari prefers PNG over ICO. */
export function homeCheffPrimaryFaviconHref(): string {
  return HOMECHEFF_BRAND_ICON_PATHS.favicon32;
}

/**
 * Metadata icons — PNG only. /favicon.ico blind-fetch is the same 32px PNG (not ICO).
 */
export function homeCheffSiteIcons(): NonNullable<Metadata["icons"]> {
  return {
    icon: [
      { url: HOMECHEFF_BRAND_ICON_PATHS.favicon32, sizes: "32x32", type: "image/png" },
      { url: HOMECHEFF_BRAND_ICON_PATHS.favicon16, sizes: "16x16", type: "image/png" },
    ],
    apple: {
      url: HOMECHEFF_BRAND_ICON_PATHS.appleTouchIcon,
      sizes: "180x180",
      type: "image/png",
    },
    shortcut: HOMECHEFF_BRAND_ICON_PATHS.favicon32,
  };
}

export function homeCheffWebManifestIcons(): Array<{
  src: string;
  sizes: string;
  type: string;
  purpose?: string;
}> {
  return [
    {
      src: HOMECHEFF_BRAND_ICON_PATHS.favicon16,
      sizes: "16x16",
      type: "image/png",
    },
    {
      src: HOMECHEFF_BRAND_ICON_PATHS.favicon32,
      sizes: "32x32",
      type: "image/png",
    },
    {
      src: HOMECHEFF_BRAND_ICON_PATHS.appleTouchIcon,
      sizes: "180x180",
      type: "image/png",
    },
    {
      src: HOMECHEFF_BRAND_ICON_PATHS.source,
      sizes: "1254x1254",
      type: "image/png",
      purpose: "any",
    },
  ];
}

export function homeCheffOpenGraphIcon(url: string): NonNullable<Metadata["openGraph"]>["images"] {
  return [
    {
      url,
      width: 1254,
      height: 1254,
      alt: HOMECHEFF_BRAND_ICON_ALT,
    },
  ];
}
