/**
 * Motion action presets added in consolidation sprint — uses existing prefill → instant pipeline.
 */

import { buildMotionActionPreset } from "@/lib/motion-action-preset-builder";
import type { MotionActionPreset } from "@/types/motion-action-presets";

export const EXPANDED_MOTION_ACTION_PRESETS: MotionActionPreset[] = [
  buildMotionActionPreset({
    id: "penalty_kick",
    category: "sports",
    title: "Penalty nemen",
    shortDescription: "Neem een penalty met spanning en focus",
    userFacingDescription:
      "Een korte sportclip waarin jij een penalty neemt — focus, aanloop en schietbeweging in een voetbalstadion.",
    motionMode: "sport",
    movement: "focused penalty run-up and kick motion",
    environment: "football stadium penalty spot",
    backgroundPrompt: "football stadium, penalty area, crowd tension, floodlights",
    promptTemplate:
      "The main character takes a penalty kick in a football stadium, focused run-up, powerful kick motion, crowd in background, cinematic sports broadcast, realistic motion.",
    feasibilityNote: "Penalty-aanloop werkt goed. Exacte balbaan is minder voorspelbaar.",
    keywords: ["penalty", "strafschop", "penalty kick"],
  }),
  buildMotionActionPreset({
    id: "goalkeeper_save",
    category: "sports",
    title: "Keeper redding",
    shortDescription: "Spectaculaire redding als keeper",
    userFacingDescription: "Jij duikt als keeper om een bal te redden in een vol stadion.",
    motionMode: "sport",
    movement: "goalkeeper diving save",
    environment: "football goal",
    backgroundPrompt: "football goal, stadium crowd, dramatic save moment",
    promptTemplate:
      "The main character as goalkeeper makes a dramatic diving save, athletic stretch, stadium crowd reacting, cinematic sports style.",
    keywords: ["keeper", "goalkeeper", "redding", "save"],
  }),
  buildMotionActionPreset({
    id: "team_celebration",
    category: "sports",
    title: "Teamviering",
    shortDescription: "Vier met je team na een overwinning",
    userFacingDescription: "Teamviering met juichen, high-fives en omhelzingen na een gewonnen wedstrijd.",
    motionMode: "celebration",
    movement: "team huddle celebration, jumping and cheering",
    environment: "sports field",
    backgroundPrompt: "sports field, teammates celebrating together, stadium lights",
    promptTemplate:
      "The main character celebrates with teammates on a sports field, group cheering, energetic celebration, cinematic sports energy.",
    keywords: ["team celebration", "teamviering", "samen juichen"],
  }),
  buildMotionActionPreset({
    id: "high_five",
    category: "sports",
    title: "High five",
    shortDescription: "Geef een enthousiaste high five",
    userFacingDescription: "Een energieke high five met zelfvertrouwen en glimlach.",
    motionMode: "celebration",
    movement: "raising hand for enthusiastic high five",
    environment: "casual sports setting",
    backgroundPrompt: "bright casual setting, friendly sports energy",
    promptTemplate:
      "The main character gives an enthusiastic high five with confident body language, friendly smile, natural motion.",
    keywords: ["high five", "high-five", "boks"],
  }),
  buildMotionActionPreset({
    id: "handshake",
    category: "business",
    title: "Hand geven",
    shortDescription: "Professionele handdruk",
    userFacingDescription: "Een zelfverzekerde professionele handdruk in een zakelijke setting.",
    motionMode: "cinematic",
    movement: "professional handshake gesture",
    environment: "modern office",
    backgroundPrompt: "modern office, professional business atmosphere",
    promptTemplate:
      "The main character offers a confident professional handshake, business attire, modern office background, natural realistic motion.",
    keywords: ["handshake", "hand geven", "handdruk"],
  }),
  buildMotionActionPreset({
    id: "group_photo",
    category: "social",
    title: "Groepsfoto",
    shortDescription: "Poseer voor een groepsfoto",
    userFacingDescription: "Je poseert vrolijk voor een groepsfoto met natuurlijke lichaamstaal.",
    motionMode: "lifestyle",
    movement: "posing for group photo, waving or smiling at camera",
    environment: "outdoor gathering",
    backgroundPrompt: "friendly group photo setting, natural daylight",
    promptTemplate:
      "The main character poses for a group photo, friendly smile, natural pose toward camera, warm social atmosphere.",
    keywords: ["group photo", "teamfoto", "groepsfoto"],
  }),
  buildMotionActionPreset({
    id: "award_ceremony",
    category: "comedy",
    title: "Award ceremony",
    shortDescription: "Ontvang een award op het podium",
    userFacingDescription: "Je loopt het podium op, ontvangt een award en bedankt het publiek.",
    motionMode: "celebration",
    movement: "walking on stage to receive award, holding trophy",
    environment: "award ceremony stage",
    backgroundPrompt: "award ceremony stage, spotlight, elegant audience, confetti",
    promptTemplate:
      "The main character walks onto an award ceremony stage, receives a trophy, waves to audience, elegant spotlight, cinematic event style.",
    keywords: ["award", "award ceremony", "prijsuitreiking", "trofee"],
  }),
  buildMotionActionPreset({
    id: "press_conference",
    category: "business",
    title: "Persconferentie",
    shortDescription: "Beantwoord vragen achter het katheder",
    userFacingDescription: "Je spreekt achter een katheder tijdens een persconferentie met microfoons.",
    motionMode: "cinematic",
    movement: "speaking at press podium with gestures",
    environment: "press conference room",
    backgroundPrompt: "press conference podium, microphones, media cameras",
    promptTemplate:
      "The main character speaks at a press conference podium, confident gestures, microphones and cameras, professional news atmosphere.",
    keywords: ["press conference", "persconferentie", "katheder"],
  }),
  buildMotionActionPreset({
    id: "podcast_clip",
    category: "social",
    title: "Podcast clip",
    shortDescription: "Praat in een podcaststudio",
    userFacingDescription: "Een korte podcastclip waarin je praat met microfoon en koptelefoon.",
    motionMode: "lifestyle",
    movement: "talking into podcast microphone with natural gestures",
    environment: "podcast studio",
    backgroundPrompt: "cozy podcast studio, microphone, headphones, warm lighting",
    promptTemplate:
      "The main character records a podcast clip, speaking into microphone with natural gestures, cozy studio lighting, conversational energy.",
    keywords: ["podcast", "podcast clip"],
  }),
  buildMotionActionPreset({
    id: "concert_moment",
    category: "dance",
    title: "Concert moment",
    shortDescription: "Optreden voor een publiek",
    userFacingDescription: "Een energiek concertmoment op het podium met publiek en lichten.",
    motionMode: "dance",
    movement: "performing on concert stage with crowd energy",
    environment: "concert stage",
    backgroundPrompt: "concert stage, colorful lights, cheering crowd",
    promptTemplate:
      "The main character performs on a concert stage, energetic body language, colorful stage lights, cheering crowd, cinematic performance.",
    keywords: ["concert", "concert moment", "optreden"],
  }),
  buildMotionActionPreset({
    id: "cooking_tutorial",
    category: "lifestyle",
    title: "Kookshow",
    shortDescription: "Kook met uitleg voor de camera",
    userFacingDescription: "Een kooktutorial waarin je ingrediënten bereidt en naar de camera praat.",
    motionMode: "lifestyle",
    movement: "cooking and explaining to camera",
    environment: "modern kitchen",
    backgroundPrompt: "bright modern kitchen, ingredients on counter, warm home atmosphere",
    promptTemplate:
      "The main character cooks in a modern kitchen, preparing food while explaining to camera, natural cooking gestures, warm inviting lighting.",
    keywords: ["cooking", "kookshow", "koken", "tutorial"],
  }),
  buildMotionActionPreset({
    id: "restaurant_service",
    category: "lifestyle",
    title: "Restaurant service",
    shortDescription: "Serveer gerechten in een restaurant",
    userFacingDescription: "Je serveert een gerecht aan tafel in een sfeervol restaurant.",
    motionMode: "lifestyle",
    movement: "serving dish to table with professional hospitality",
    environment: "upscale restaurant",
    backgroundPrompt: "upscale restaurant interior, warm ambient lighting, dining tables",
    promptTemplate:
      "The main character serves food in an upscale restaurant, professional hospitality gestures, warm restaurant ambiance, cinematic lifestyle shot.",
    keywords: ["restaurant", "serveren", "service"],
  }),
  buildMotionActionPreset({
    id: "gardening_activity",
    category: "lifestyle",
    title: "Tuinieren",
    shortDescription: "Werk in de tuin met planten",
    userFacingDescription: "Een rustig tuinmoment waarin je planten verzorgt in de zon.",
    motionMode: "lifestyle",
    movement: "gardening, tending plants peacefully",
    environment: "sunny garden",
    backgroundPrompt: "sunny garden, plants, flowers, peaceful outdoor setting",
    promptTemplate:
      "The main character gardens peacefully in a sunny garden, tending plants, calm natural motion, warm daylight.",
    keywords: ["gardening", "tuinieren", "tuin"],
  }),
  buildMotionActionPreset({
    id: "market_vendor",
    category: "lifestyle",
    title: "Marktkraam",
    shortDescription: "Verkoop op een levendige markt",
    userFacingDescription: "Je presenteert producten op een kleurrijke marktkraam.",
    motionMode: "lifestyle",
    movement: "presenting products at market stall",
    environment: "outdoor market",
    backgroundPrompt: "vibrant outdoor market, fresh produce, busy market atmosphere",
    promptTemplate:
      "The main character presents products at a vibrant outdoor market stall, friendly gestures, colorful market background, lively atmosphere.",
    keywords: ["market", "markt", "vendor", "kraam"],
  }),
  buildMotionActionPreset({
    id: "shopping_trip",
    category: "lifestyle",
    title: "Shopping trip",
    shortDescription: "Winkel met stijl in de stad",
    userFacingDescription: "Een lifestyle shoppingmoment in een stijlvolle winkelstraat.",
    motionMode: "lifestyle",
    movement: "walking through shops carrying bags",
    environment: "shopping street",
    backgroundPrompt: "stylish shopping street, boutique windows, urban lifestyle",
    promptTemplate:
      "The main character enjoys a shopping trip on a stylish street, walking with bags, casual confident motion, urban lifestyle aesthetic.",
    keywords: ["shopping", "winkelen", "shopping trip"],
  }),
  buildMotionActionPreset({
    id: "walking_city",
    category: "lifestyle",
    title: "Door de stad lopen",
    shortDescription: "Wandel ontspannen door de stad",
    userFacingDescription: "Een rustige wandeling door een mooie stad met natuurlijke beweging.",
    motionMode: "lifestyle",
    movement: "relaxed city walking",
    environment: "city street",
    backgroundPrompt: "beautiful city street, urban architecture, golden hour light",
    promptTemplate:
      "The main character walks relaxed through a beautiful city street, natural walking motion, golden hour urban atmosphere.",
    keywords: ["walking city", "stad lopen", "wandelen"],
  }),
  buildMotionActionPreset({
    id: "influencer_reel",
    category: "social",
    title: "Influencer reel",
    shortDescription: "Korte social reel voor je feed",
    userFacingDescription: "Een trendy influencer-reel met energie en directe blik naar camera.",
    motionMode: "lifestyle",
    movement: "trendy social reel gestures toward camera",
    environment: "stylish urban backdrop",
    backgroundPrompt: "trendy urban backdrop, social media aesthetic, vibrant colors",
    promptTemplate:
      "The main character films a trendy influencer reel, energetic gestures toward camera, stylish urban backdrop, social media aesthetic.",
    keywords: ["influencer", "reel", "social media"],
  }),
  buildMotionActionPreset({
    id: "vlog_intro",
    category: "social",
    title: "Vlog intro",
    shortDescription: "Start je vlog met energie",
    userFacingDescription: "Een vlog-intro waarin je de camera begroet en je verhaal start.",
    motionMode: "lifestyle",
    movement: "vlog intro wave and talking to camera",
    environment: "casual vlog setting",
    backgroundPrompt: "casual vlog setting, natural light, friendly creator vibe",
    promptTemplate:
      "The main character opens a vlog with a friendly wave and talking to camera, casual creator energy, natural lighting.",
    keywords: ["vlog", "vlog intro"],
  }),
  buildMotionActionPreset({
    id: "creator_intro",
    category: "social",
    title: "Creator intro",
    shortDescription: "Stel jezelf voor als creator",
    userFacingDescription: "Een korte creator-intro met persoonlijke uitstraling.",
    motionMode: "lifestyle",
    movement: "creator introduction to camera",
    environment: "creator studio corner",
    backgroundPrompt: "creator studio setup, ring light, personal branding backdrop",
    promptTemplate:
      "The main character introduces themselves as a creator to camera, confident friendly energy, creator studio backdrop.",
    keywords: ["creator intro", "introductie"],
  }),
  buildMotionActionPreset({
    id: "product_unboxing",
    category: "business",
    title: "Product uitpakken",
    shortDescription: "Unbox een product voor de camera",
    userFacingDescription: "Je pakt een product uit en toont het enthousiast aan de kijker.",
    motionMode: "cinematic",
    movement: "unboxing product with reveal gestures",
    environment: "clean product desk",
    backgroundPrompt: "clean product desk, soft studio lighting, minimal background",
    promptTemplate:
      "The main character unboxes a product on camera, reveal gestures, clean product desk, soft studio lighting, commercial style.",
    keywords: ["unboxing", "uitpakken", "product"],
  }),
  buildMotionActionPreset({
    id: "product_launch",
    category: "business",
    title: "Product launch",
    shortDescription: "Onthul een nieuw product",
    userFacingDescription: "Een productlancering met dramatische onthulling en zelfvertrouwen.",
    motionMode: "cinematic",
    movement: "dramatic product reveal presentation",
    environment: "launch event stage",
    backgroundPrompt: "product launch stage, spotlight, sleek modern branding",
    promptTemplate:
      "The main character reveals a new product on a launch stage, dramatic presentation gesture, spotlight, premium commercial style.",
    keywords: ["product launch", "lancering"],
  }),
  buildMotionActionPreset({
    id: "product_showcase",
    category: "business",
    title: "Product showcase",
    shortDescription: "Toon je product helder",
    userFacingDescription: "Een heldere productshowcase met focus op het product in je handen.",
    motionMode: "cinematic",
    movement: "showcasing product to camera",
    environment: "studio product shot",
    backgroundPrompt: "clean studio background, product focus lighting",
    promptTemplate:
      "The main character showcases a product to camera, clear presentation gestures, clean studio lighting, commercial product video style.",
    keywords: ["product showcase", "productshowcase"],
  }),
  buildMotionActionPreset({
    id: "brand_reveal",
    category: "business",
    title: "Brand reveal",
    shortDescription: "Onthul je merk met impact",
    userFacingDescription: "Een merkonthulling met sterke visuele presentatie.",
    motionMode: "cinematic",
    movement: "brand reveal presentation gesture",
    environment: "branded stage",
    backgroundPrompt: "branded stage, dramatic lighting, premium marketing aesthetic",
    promptTemplate:
      "The main character performs a brand reveal presentation, confident gesture, branded stage lighting, premium marketing cinematic style.",
    keywords: ["brand reveal", "merk onthulling"],
  }),
  buildMotionActionPreset({
    id: "business_presentation",
    category: "business",
    title: "Presentatie",
    shortDescription: "Houd een zakelijke presentatie",
    userFacingDescription: "Je presenteert zelfverzekerd met slides en gebaren op kantoor.",
    motionMode: "cinematic",
    movement: "business presentation with confident gestures",
    environment: "conference room",
    backgroundPrompt: "modern conference room, presentation screen, professional setting",
    promptTemplate:
      "The main character gives a business presentation in a conference room, confident gestures, professional atmosphere, realistic motion.",
    keywords: ["presentation", "presentatie", "pitch"],
  }),
  buildMotionActionPreset({
    id: "startup_pitch",
    category: "business",
    title: "Startup pitch",
    shortDescription: "Pitch je idee aan investeerders",
    userFacingDescription: "Een energieke startup pitch met overtuigende lichaamstaal.",
    motionMode: "cinematic",
    movement: "startup pitch presentation gestures",
    environment: "startup pitch room",
    backgroundPrompt: "startup pitch event, investors in background, modern office",
    promptTemplate:
      "The main character delivers a startup pitch, passionate gestures, modern pitch room, convincing entrepreneurial energy.",
    keywords: ["startup pitch", "pitch", "investeerders"],
  }),
  buildMotionActionPreset({
    id: "conference_speaker",
    category: "business",
    title: "Conference speaker",
    shortDescription: "Spreek op een conferentie",
    userFacingDescription: "Je spreekt op een groot conferentiepodium voor een publiek.",
    motionMode: "cinematic",
    movement: "speaking on conference stage",
    environment: "conference hall",
    backgroundPrompt: "large conference hall, stage, audience, professional event lighting",
    promptTemplate:
      "The main character speaks on a conference stage, professional gestures, large audience, event lighting, cinematic keynote style.",
    keywords: ["conference", "speaker", "keynote"],
  }),
  buildMotionActionPreset({
    id: "networking_event",
    category: "business",
    title: "Networking event",
    shortDescription: "Netwerk op een zakelijk event",
    userFacingDescription: "Een networkingmoment met gesprekken en handdrukken op een event.",
    motionMode: "lifestyle",
    movement: "networking at business event, conversational gestures",
    environment: "business networking event",
    backgroundPrompt: "business networking event, elegant venue, professionals mingling",
    promptTemplate:
      "The main character networks at a business event, conversational gestures, elegant venue, professional social atmosphere.",
    keywords: ["networking", "netwerken", "event"],
  }),
  buildMotionActionPreset({
    id: "mascot_introduction",
    category: "mascots",
    title: "Mascotte introductie",
    shortDescription: "Stel je mascotte voor",
    userFacingDescription: "Je mascotte stelt zich vriendelijk voor aan het publiek.",
    motionMode: "cinematic",
    movement: "mascot friendly introduction wave",
    environment: "brand event space",
    backgroundPrompt: "colorful brand event space, friendly mascot atmosphere",
    promptTemplate:
      "The main character mascot introduces itself with a friendly wave, preserve exact mascot face colors and proportions, lively brand event background.",
    feasibilityNote: "Werkt het best met een motion-ready mascotte of duidelijke bronfoto.",
    keywords: ["mascot introduction", "mascotte introductie"],
  }),
  buildMotionActionPreset({
    id: "mascot_greeting",
    category: "mascots",
    title: "Mascotte begroeting",
    shortDescription: "Mascotte begroet het publiek",
    userFacingDescription: "Je mascotte zwaait vrolijk en begroet fans.",
    motionMode: "celebration",
    movement: "mascot waving greeting to crowd",
    environment: "public event",
    backgroundPrompt: "public event, fans, colorful mascot-friendly setting",
    promptTemplate:
      "The main character mascot greets the crowd with a cheerful wave, preserve mascot identity exactly, friendly public event atmosphere.",
    keywords: ["mascot greeting", "mascotte begroeting"],
  }),
  buildMotionActionPreset({
    id: "mascot_celebration",
    category: "mascots",
    title: "Mascotte viering",
    shortDescription: "Mascotte viert een moment",
    userFacingDescription: "Je mascotte springt en viert een feestelijk moment.",
    motionMode: "celebration",
    movement: "mascot celebratory jump and cheer",
    environment: "festive venue",
    backgroundPrompt: "festive venue, confetti, cheerful crowd",
    promptTemplate:
      "The main character mascot celebrates with joyful jump and cheer, preserve exact mascot design, festive confetti atmosphere.",
    keywords: ["mascot celebration", "mascotte viering"],
  }),
  buildMotionActionPreset({
    id: "mascot_presentation",
    category: "mascots",
    title: "Mascotte presentatie",
    shortDescription: "Mascotte presenteert op podium",
    userFacingDescription: "Je mascotte presenteert enthousiast op een podium.",
    motionMode: "cinematic",
    movement: "mascot presenting on stage",
    environment: "stage with audience",
    backgroundPrompt: "stage, spotlight, audience, mascot presentation event",
    promptTemplate:
      "The main character mascot presents on stage with enthusiastic gestures, preserve mascot identity, spotlight and audience.",
    keywords: ["mascot presentation", "mascotte presentatie"],
  }),
  buildMotionActionPreset({
    id: "mascot_commercial",
    category: "mascots",
    title: "Mascotte commercial",
    shortDescription: "Mascotte in een commercial",
    userFacingDescription: "Een korte commercial met je mascotte in een levendige scène.",
    motionMode: "cinematic",
    movement: "mascot commercial performance gestures",
    environment: "branded commercial set",
    backgroundPrompt: "branded commercial set, vibrant marketing colors, product placement",
    promptTemplate:
      "The main character mascot stars in a short commercial, lively gestures, preserve exact mascot branding, vibrant commercial set.",
    keywords: ["mascot commercial", "mascotte commercial"],
  }),
  buildMotionActionPreset({
    id: "superhero_landing",
    category: "adventure",
    title: "Superheld landing",
    shortDescription: "Epische superheldenlanding",
    userFacingDescription: "Een dramatische superheldenlanding met cape en heldhaftige pose.",
    motionMode: "cinematic",
    movement: "superhero landing pose with cape",
    environment: "urban rooftop",
    backgroundPrompt: "urban rooftop, dramatic sky, cinematic superhero atmosphere",
    promptTemplate:
      "The main character performs a cinematic superhero landing pose, dramatic cape motion, urban rooftop, epic lighting.",
    keywords: ["superhero", "superheld", "landing"],
  }),
  buildMotionActionPreset({
    id: "festival_appearance",
    category: "adventure",
    title: "Festival optreden",
    shortDescription: "Verschijn op een festival",
    userFacingDescription: "Je maakt een energieke entree op een muziekfestival.",
    motionMode: "celebration",
    movement: "festival entrance with crowd energy",
    environment: "music festival",
    backgroundPrompt: "music festival, stage lights, large crowd, festive energy",
    promptTemplate:
      "The main character makes an energetic festival appearance, crowd and stage lights, festive music festival atmosphere.",
    keywords: ["festival", "festival appearance"],
  }),
  buildMotionActionPreset({
    id: "travel_vlog",
    category: "adventure",
    title: "Reisvlog",
    shortDescription: "Leg een reismoment vast",
    userFacingDescription: "Een reisvlogmoment op een iconische locatie.",
    motionMode: "lifestyle",
    movement: "travel vlog talking to camera at scenic location",
    environment: "scenic travel destination",
    backgroundPrompt: "scenic travel destination, landmark, adventure travel vibe",
    promptTemplate:
      "The main character films a travel vlog moment at a scenic destination, talking to camera, adventure travel atmosphere.",
    keywords: ["travel vlog", "reisvlog", "wereldreis"],
  }),
  buildMotionActionPreset({
    id: "airport_arrival",
    category: "adventure",
    title: "Luchthaven aankomst",
    shortDescription: "Kom aan op de luchthaven",
    userFacingDescription: "Je loopt zelfverzekerd door de luchthaven met koffer.",
    motionMode: "cinematic",
    movement: "walking through airport terminal with luggage",
    environment: "airport terminal",
    backgroundPrompt: "modern airport terminal, travel atmosphere, glass architecture",
    promptTemplate:
      "The main character walks through an airport terminal with luggage, confident travel energy, modern airport architecture.",
    keywords: ["airport", "luchthaven", "arrival"],
  }),
  buildMotionActionPreset({
    id: "luxury_entrance",
    category: "adventure",
    title: "Luxe entree",
    shortDescription: "Maak een luxe entree",
    userFacingDescription: "Een luxe entree met stijlvolle outfit en dramatische belichting.",
    motionMode: "cinematic",
    movement: "luxury entrance walk",
    environment: "luxury venue entrance",
    backgroundPrompt: "luxury venue entrance, red accents, elegant lighting",
    promptTemplate:
      "The main character makes a luxury entrance, confident walk, elegant venue, dramatic upscale lighting.",
    keywords: ["luxury entrance", "luxe entree"],
  }),
  buildMotionActionPreset({
    id: "photoshoot",
    category: "social",
    title: "Fotoshoot",
    shortDescription: "Poseer tijdens een fotoshoot",
    userFacingDescription: "Een professionele fotoshoot met verschillende poses.",
    motionMode: "lifestyle",
    movement: "model poses during photoshoot",
    environment: "photo studio",
    backgroundPrompt: "professional photo studio, softboxes, clean backdrop",
    promptTemplate:
      "The main character poses during a professional photoshoot, natural model poses, studio lighting, fashion photography style.",
    keywords: ["photoshoot", "fotoshoot"],
  }),
  buildMotionActionPreset({
    id: "wedding_entrance",
    category: "social",
    title: "Bruiloft entree",
    shortDescription: "Maak je entree op een bruiloft",
    userFacingDescription: "Een elegante bruilofts entree met vreugde en stijl.",
    motionMode: "cinematic",
    movement: "elegant wedding entrance walk",
    environment: "wedding venue",
    backgroundPrompt: "elegant wedding venue, flowers, romantic lighting",
    promptTemplate:
      "The main character makes an elegant wedding entrance, graceful walk, romantic venue, soft cinematic lighting.",
    keywords: ["wedding", "bruiloft", "entree"],
  }),
  buildMotionActionPreset({
    id: "birthday_celebration",
    category: "social",
    title: "Verjaardag vieren",
    shortDescription: "Vier je verjaardag",
    userFacingDescription: "Je viert je verjaardag met taart en vrolijke energie.",
    motionMode: "celebration",
    movement: "birthday celebration with cake",
    environment: "birthday party",
    backgroundPrompt: "birthday party, balloons, cake, cheerful decorations",
    promptTemplate:
      "The main character celebrates a birthday with cheerful gestures, birthday cake and balloons, festive party atmosphere.",
    keywords: ["birthday", "verjaardag"],
  }),
  buildMotionActionPreset({
    id: "graduation_moment",
    category: "social",
    title: "Diploma-uitreiking",
    shortDescription: "Vier je diploma",
    userFacingDescription: "Je viert je afstuderen met diploma en trots gebaar.",
    motionMode: "celebration",
    movement: "graduation celebration holding diploma",
    environment: "graduation ceremony",
    backgroundPrompt: "graduation ceremony, academic gowns, proud celebration",
    promptTemplate:
      "The main character celebrates graduation, holding diploma proudly, academic ceremony background, joyful achievement moment.",
    keywords: ["graduation", "diploma", "afstuderen"],
  }),
  buildMotionActionPreset({
    id: "fitness_workout",
    category: "sports",
    title: "Fitness workout",
    shortDescription: "Train in de sportschool",
    userFacingDescription: "Een energieke fitness workout in de gym.",
    motionMode: "sport",
    movement: "fitness workout exercise motion",
    environment: "gym",
    backgroundPrompt: "modern gym, fitness equipment, energetic workout atmosphere",
    promptTemplate:
      "The main character performs a fitness workout in a modern gym, energetic exercise motion, athletic atmosphere.",
    keywords: ["fitness", "workout", "gym"],
  }),
  buildMotionActionPreset({
    id: "running_challenge",
    category: "sports",
    title: "Hardloop challenge",
    shortDescription: "Ren een uitdagende route",
    userFacingDescription: "Een hardloopchallenge met focus en doorzettingsvermogen.",
    motionMode: "sport",
    movement: "running challenge sprint motion",
    environment: "outdoor running track",
    backgroundPrompt: "outdoor running path, athletic challenge atmosphere",
    promptTemplate:
      "The main character runs an athletic challenge route, determined running motion, outdoor track atmosphere.",
    keywords: ["running", "hardlopen", "challenge"],
  }),
  buildMotionActionPreset({
    id: "boxing_entrance",
    category: "sports",
    title: "Boks entree",
    shortDescription: "Maak je entree in de ring",
    userFacingDescription: "Een krachtige boksersentree de ring in.",
    motionMode: "sport",
    movement: "boxer ring entrance walk",
    environment: "boxing ring",
    backgroundPrompt: "boxing ring, crowd, dramatic sports lighting",
    promptTemplate:
      "The main character makes a boxer ring entrance, confident athletic walk, boxing ring, dramatic crowd lighting.",
    keywords: ["boxing", "boksen", "ring"],
  }),
  buildMotionActionPreset({
    id: "training_montage",
    category: "sports",
    title: "Training montage",
    shortDescription: "Train hard in montage-stijl",
    userFacingDescription: "Een dynamische trainingmontage met verschillende oefeningen.",
    motionMode: "sport",
    movement: "dynamic training montage exercises",
    environment: "training facility",
    backgroundPrompt: "training facility, athletic montage energy, motivational atmosphere",
    promptTemplate:
      "The main character performs dynamic training exercises in montage style, athletic motion, motivational sports atmosphere.",
    keywords: ["training montage", "training"],
  }),
  buildMotionActionPreset({
    id: "dance_challenge",
    category: "dance",
    title: "Dans challenge",
    shortDescription: "Doe mee aan een dans challenge",
    userFacingDescription: "Een energieke danschallenge met trendy moves.",
    motionMode: "dance",
    movement: "trendy dance challenge choreography",
    environment: "dance studio",
    backgroundPrompt: "dance studio, mirrors, energetic dance challenge vibe",
    promptTemplate:
      "The main character performs a trendy dance challenge choreography, energetic dance moves, studio mirrors, social dance style.",
    keywords: ["dance challenge", "dans challenge"],
  }),
  buildMotionActionPreset({
    id: "tiktok_trend",
    category: "social",
    title: "TikTok trend",
    shortDescription: "Doe een trending move",
    userFacingDescription: "Een korte trendvideo in TikTok-stijl.",
    motionMode: "lifestyle",
    movement: "trending social media dance or gesture",
    environment: "trendy social backdrop",
    backgroundPrompt: "trendy social media backdrop, vertical video aesthetic",
    promptTemplate:
      "The main character performs a trending social media move, vertical video style, trendy backdrop, energetic creator vibe.",
    keywords: ["tiktok", "trend", "viral"],
  }),
];

/** NLP keywords for expanded presets (merged into PRESET_KEYWORD_RULES). */
export const EXPANDED_PRESET_KEYWORD_RULES: Array<{
  id: MotionActionPreset["id"];
  keywords: string[];
}> = [
  { id: "penalty_kick", keywords: ["penalty", "strafschop"] },
  { id: "goalkeeper_save", keywords: ["keeper", "redding", "save"] },
  { id: "team_celebration", keywords: ["teamviering", "team celebration"] },
  { id: "high_five", keywords: ["high five", "high-five"] },
  { id: "handshake", keywords: ["handshake", "handdruk"] },
  { id: "group_photo", keywords: ["groepsfoto", "teamfoto"] },
  { id: "award_ceremony", keywords: ["award ceremony", "prijsuitreiking"] },
  { id: "press_conference", keywords: ["persconferentie", "press conference"] },
  { id: "podcast_clip", keywords: ["podcast"] },
  { id: "concert_moment", keywords: ["concert moment"] },
  { id: "cooking_tutorial", keywords: ["kookshow", "cooking tutorial"] },
  { id: "restaurant_service", keywords: ["restaurant service"] },
  { id: "gardening_activity", keywords: ["tuinieren", "gardening"] },
  { id: "market_vendor", keywords: ["marktkraam", "market vendor"] },
  { id: "shopping_trip", keywords: ["shopping trip", "winkelen"] },
  { id: "walking_city", keywords: ["stad lopen", "walking city"] },
  { id: "influencer_reel", keywords: ["influencer reel"] },
  { id: "vlog_intro", keywords: ["vlog intro"] },
  { id: "creator_intro", keywords: ["creator intro"] },
  { id: "product_unboxing", keywords: ["unboxing", "uitpakken"] },
  { id: "product_launch", keywords: ["product launch", "lancering"] },
  { id: "product_showcase", keywords: ["product showcase"] },
  { id: "brand_reveal", keywords: ["brand reveal"] },
  { id: "business_presentation", keywords: ["presentatie", "presentation"] },
  { id: "startup_pitch", keywords: ["startup pitch", "pitch"] },
  { id: "conference_speaker", keywords: ["conference speaker", "keynote"] },
  { id: "networking_event", keywords: ["networking"] },
  { id: "mascot_introduction", keywords: ["mascot introduction", "mascotte introductie"] },
  { id: "mascot_greeting", keywords: ["mascot greeting"] },
  { id: "mascot_celebration", keywords: ["mascot celebration"] },
  { id: "mascot_presentation", keywords: ["mascot presentation"] },
  { id: "mascot_commercial", keywords: ["mascot commercial"] },
  { id: "superhero_landing", keywords: ["superhero", "superheld"] },
  { id: "festival_appearance", keywords: ["festival"] },
  { id: "travel_vlog", keywords: ["travel vlog", "reisvlog"] },
  { id: "airport_arrival", keywords: ["airport", "luchthaven"] },
  { id: "luxury_entrance", keywords: ["luxury entrance", "luxe entree"] },
  { id: "photoshoot", keywords: ["photoshoot", "fotoshoot"] },
  { id: "wedding_entrance", keywords: ["wedding", "bruiloft"] },
  { id: "birthday_celebration", keywords: ["birthday", "verjaardag"] },
  { id: "graduation_moment", keywords: ["graduation", "diploma"] },
  { id: "fitness_workout", keywords: ["fitness", "workout"] },
  { id: "running_challenge", keywords: ["running challenge"] },
  { id: "boxing_entrance", keywords: ["boxing", "boksen"] },
  { id: "training_montage", keywords: ["training montage"] },
  { id: "dance_challenge", keywords: ["dance challenge"] },
  { id: "tiktok_trend", keywords: ["tiktok", "trend"] },
];
