/** Re-exports storyboard timing helpers (defined in story-overlay-templates). */
export {
  clampStorySceneDurationForVidu,
  getSceneTimingWindows,
  getSceneTransitionDurationSeconds,
  getStoryboardDurationSeconds,
  getStoryTransitionDurationSeconds,
  getViduTotalFromStoryboardSegments,
  hasCustomTransitionDurations,
  hasPerSceneDurations,
  normalizeStoryboardScenes,
  resolveViduSegmentDurationsFromStoryboard,
  splitSequenceSceneTiming,
  storyDurationFromGlobalFallback,
  normalizeStorySceneDurationSeconds,
  sanitizeSceneTextField,
  SEQUENCE_HERO_FINALE_SHARE,
  SEQUENCE_LINES_SHARE,
  STORY_SCENE_DURATION_ALLOWED,
  STORY_SCENE_DURATION_OPTIONS,
  MAX_HERO_FINALE_TEXT_CHARS,
  MAX_SCENE_LINE_CHARS,
  type SceneTimingWindow,
  type StorySceneDurationSeconds,
} from "@/lib/story-overlay-templates";
