export const PRICING_CATALOG_CATEGORIES = [
  "images",
  "characters",
  "video_motion",
  "voice",
  "music",
  "sound_effects",
  "translation",
  "subtitles",
  "editor",
  "publish",
  "assistant",
  "utility",
] as const;

export type PricingCatalogCategory = (typeof PRICING_CATALOG_CATEGORIES)[number];

export type PricingCatalogActionMeta = {
  actionType: string;
  category: PricingCatalogCategory;
  displayNameNl: string;
  displayNameEn: string;
  descriptionNl: string;
  descriptionEn: string;
  sortOrder: number;
  visibleInCatalog: boolean;
  isFree: boolean;
  /** Seeded into StudioPricingRule.notes when sync-defaults creates the row. */
  defaultAdminNotes?: string;
};

/** Default catalog metadata — merged with DB overrides and registry costs. */
export const PRICING_CATALOG_ACTION_META: Record<string, PricingCatalogActionMeta> = {
  ai_analysis: {
    actionType: "ai_analysis",
    category: "utility",
    displayNameNl: "AI-analyse",
    displayNameEn: "AI analysis",
    descriptionNl: "Analyseer storyboard of scène-inhoud met AI.",
    descriptionEn: "Analyze storyboard or scene content with AI.",
    sortOrder: 100,
    visibleInCatalog: true,
    isFree: false,
  },
  storyboard_generation: {
    actionType: "storyboard_generation",
    category: "utility",
    displayNameNl: "Storyboard genereren",
    displayNameEn: "Storyboard generation",
    descriptionNl: "Genereer een storyboard op basis van je briefing.",
    descriptionEn: "Generate a storyboard from your brief.",
    sortOrder: 110,
    visibleInCatalog: true,
    isFree: false,
  },
  prompt_improvement: {
    actionType: "prompt_improvement",
    category: "utility",
    displayNameNl: "Prompt verbeteren",
    displayNameEn: "Prompt improvement",
    descriptionNl: "Verbeter prompts voor betere generaties.",
    descriptionEn: "Improve prompts for better generations.",
    sortOrder: 120,
    visibleInCatalog: false,
    isFree: false,
  },
  voice_suggestion: {
    actionType: "voice_suggestion",
    category: "utility",
    displayNameNl: "Stem-suggestie",
    displayNameEn: "Voice suggestion",
    descriptionNl: "AI-suggestie voor passende stem.",
    descriptionEn: "AI suggestion for a matching voice.",
    sortOrder: 130,
    visibleInCatalog: false,
    isFree: false,
  },
  music_suggestion: {
    actionType: "music_suggestion",
    category: "utility",
    displayNameNl: "Muziek-suggestie",
    displayNameEn: "Music suggestion",
    descriptionNl: "AI-suggestie voor achtergrondmuziek.",
    descriptionEn: "AI suggestion for background music.",
    sortOrder: 140,
    visibleInCatalog: false,
    isFree: false,
  },
  character_generation: {
    actionType: "character_generation",
    category: "characters",
    displayNameNl: "Personage genereren",
    displayNameEn: "Character generation",
    descriptionNl: "Maak een nieuw Studio-personage of mascotte.",
    descriptionEn: "Create a new Studio character or mascot.",
    sortOrder: 200,
    visibleInCatalog: true,
    isFree: false,
  },
  location_generation: {
    actionType: "location_generation",
    category: "characters",
    displayNameNl: "Locatie genereren",
    displayNameEn: "Location generation",
    descriptionNl: "Genereer een locatie of achtergrond.",
    descriptionEn: "Generate a location or background.",
    sortOrder: 210,
    visibleInCatalog: true,
    isFree: false,
  },
  prop_generation: {
    actionType: "prop_generation",
    category: "characters",
    displayNameNl: "Prop genereren",
    displayNameEn: "Prop generation",
    descriptionNl: "Genereer een prop of object voor je scène.",
    descriptionEn: "Generate a prop or object for your scene.",
    sortOrder: 220,
    visibleInCatalog: true,
    isFree: false,
  },
  world_generation: {
    actionType: "world_generation",
    category: "characters",
    displayNameNl: "Wereldprofiel genereren",
    displayNameEn: "World profile generation",
    descriptionNl: "Bouw een wereldprofiel voor consistente producties.",
    descriptionEn: "Build a world profile for consistent productions.",
    sortOrder: 230,
    visibleInCatalog: true,
    isFree: false,
  },
  scene_generation: {
    actionType: "scene_generation",
    category: "images",
    displayNameNl: "Scène-afbeelding genereren",
    displayNameEn: "Scene image generation",
    descriptionNl: "Genereer een scène-still voor je storyboard.",
    descriptionEn: "Generate a scene still for your storyboard.",
    sortOrder: 300,
    visibleInCatalog: true,
    isFree: false,
  },
  voice_generation: {
    actionType: "voice_generation",
    category: "voice",
    displayNameNl: "Voice-over genereren",
    displayNameEn: "Voice generation",
    descriptionNl: "Genereer voice-over met ElevenLabs.",
    descriptionEn: "Generate voice-over with ElevenLabs.",
    sortOrder: 400,
    visibleInCatalog: true,
    isFree: false,
  },
  voice_clone: {
    actionType: "voice_clone",
    category: "voice",
    displayNameNl: "Stem klonen",
    displayNameEn: "Voice clone",
    descriptionNl: "Kloon een stem voor hergebruik in producties. Voice cloning heeft hogere providerkosten dan standaard stemgeneratie.",
    descriptionEn: "Clone a voice for reuse in productions. Voice cloning has higher provider costs than standard voice generation.",
    sortOrder: 410,
    visibleInCatalog: true,
    isFree: false,
    defaultAdminNotes: "Voice cloning has a higher provider cost than standard voice generation.",
  },
  subtitle_transcription: {
    actionType: "subtitle_transcription",
    category: "subtitles",
    displayNameNl: "Ondertiteling transcriberen",
    displayNameEn: "Subtitle transcription",
    descriptionNl: "Transcriptie voor ondertitels.",
    descriptionEn: "Transcription for subtitles.",
    sortOrder: 500,
    visibleInCatalog: true,
    isFree: false,
  },
  music_generation: {
    actionType: "music_generation",
    category: "music",
    displayNameNl: "Muziek genereren",
    displayNameEn: "Music generation",
    descriptionNl: "Genereer achtergrondmuziek voor je video.",
    descriptionEn: "Generate background music for your video.",
    sortOrder: 600,
    visibleInCatalog: true,
    isFree: false,
  },
  sfx_generation: {
    actionType: "sfx_generation",
    category: "sound_effects",
    displayNameNl: "Geluidseffect genereren",
    displayNameEn: "Sound effect generation",
    descriptionNl: "Genereer sound effects voor je scène.",
    descriptionEn: "Generate sound effects for your scene.",
    sortOrder: 610,
    visibleInCatalog: true,
    isFree: false,
  },
  assistant_interpret: {
    actionType: "assistant_interpret",
    category: "assistant",
    displayNameNl: "Assistant interpretatie",
    displayNameEn: "Assistant interpretation",
    descriptionNl: "AI-interpretatie van je verzoek in de assistant.",
    descriptionEn: "AI interpretation of your request in the assistant.",
    sortOrder: 700,
    visibleInCatalog: false,
    isFree: false,
  },
  ocr_scan: {
    actionType: "ocr_scan",
    category: "utility",
    displayNameNl: "OCR-scan",
    displayNameEn: "OCR scan",
    descriptionNl: "Tekst herkennen in afbeeldingen.",
    descriptionEn: "Recognize text in images.",
    sortOrder: 150,
    visibleInCatalog: false,
    isFree: false,
  },
  vision_analysis: {
    actionType: "vision_analysis",
    category: "utility",
    displayNameNl: "Vision-analyse",
    displayNameEn: "Vision analysis",
    descriptionNl: "Visuele analyse van afbeeldingen.",
    descriptionEn: "Visual analysis of images.",
    sortOrder: 160,
    visibleInCatalog: false,
    isFree: false,
  },
  premium_vision_analysis: {
    actionType: "premium_vision_analysis",
    category: "utility",
    displayNameNl: "Uitgebreide AI-analyse",
    displayNameEn: "Extended AI analysis",
    descriptionNl:
      "Herkent extra details zoals ogen, mond, haar, kleding, pose en achtergrond.",
    descriptionEn:
      "Detects extra details such as eyes, mouth, hair, clothing, pose, and background.",
    sortOrder: 165,
    visibleInCatalog: true,
    isFree: false,
  },
  motion_render: {
    actionType: "motion_render",
    category: "video_motion",
    displayNameNl: "Motion-render",
    displayNameEn: "Motion render",
    descriptionNl: "Render een AI-videoclip (bijv. doelpuntviering of social clip).",
    descriptionEn: "Render an AI video clip (e.g. goal celebration or social clip).",
    sortOrder: 800,
    visibleInCatalog: true,
    isFree: false,
  },
  publish_photo_story: {
    actionType: "publish_photo_story",
    category: "publish",
    displayNameNl: "Photo Story export",
    displayNameEn: "Photo story export",
    descriptionNl: "Exporteer een photo story naar MP4.",
    descriptionEn: "Export a photo story to MP4.",
    sortOrder: 900,
    visibleInCatalog: true,
    isFree: false,
  },
  publish_slideshow: {
    actionType: "publish_slideshow",
    category: "publish",
    displayNameNl: "Slideshow export",
    displayNameEn: "Slideshow export",
    descriptionNl: "Exporteer een slideshow-video.",
    descriptionEn: "Export a slideshow video.",
    sortOrder: 910,
    visibleInCatalog: true,
    isFree: false,
  },
  publish_voice_message: {
    actionType: "publish_voice_message",
    category: "publish",
    displayNameNl: "Voice message export",
    displayNameEn: "Voice message export",
    descriptionNl: "Exporteer een voice message video.",
    descriptionEn: "Export a voice message video.",
    sortOrder: 920,
    visibleInCatalog: false,
    isFree: false,
  },
  publish_poster_export: {
    actionType: "publish_poster_export",
    category: "publish",
    displayNameNl: "Poster export",
    displayNameEn: "Poster export",
    descriptionNl: "Exporteer een poster of still.",
    descriptionEn: "Export a poster or still.",
    sortOrder: 930,
    visibleInCatalog: true,
    isFree: false,
  },
  publish_mp4_export: {
    actionType: "publish_mp4_export",
    category: "publish",
    displayNameNl: "MP4 export",
    displayNameEn: "MP4 export",
    descriptionNl: "Exporteer je productie als MP4.",
    descriptionEn: "Export your production as MP4.",
    sortOrder: 940,
    visibleInCatalog: true,
    isFree: false,
  },
  translation_export: {
    actionType: "translation_export",
    category: "translation",
    displayNameNl: "Vertaling export",
    displayNameEn: "Translation export",
    descriptionNl: "Exporteer vertaalde versies van je video.",
    descriptionEn: "Export translated versions of your video.",
    sortOrder: 550,
    visibleInCatalog: true,
    isFree: false,
  },
  image_generation: {
    actionType: "image_generation",
    category: "editor",
    displayNameNl: "Afbeelding genereren",
    displayNameEn: "Image generation",
    descriptionNl: "Genereer een afbeelding in de Editor.",
    descriptionEn: "Generate an image in the Editor.",
    sortOrder: 350,
    visibleInCatalog: true,
    isFree: false,
  },
  image_edit: {
    actionType: "image_edit",
    category: "editor",
    displayNameNl: "Afbeelding bewerken",
    displayNameEn: "Image edit",
    descriptionNl: "Bewerk een afbeelding met AI in de Editor.",
    descriptionEn: "Edit an image with AI in the Editor.",
    sortOrder: 360,
    visibleInCatalog: true,
    isFree: false,
  },
  transformation_session: {
    actionType: "transformation_session",
    category: "editor",
    displayNameNl: "Transformatie-sessie",
    displayNameEn: "Transformation session",
    descriptionNl: "Editor transformatie-sessie met meerdere stappen.",
    descriptionEn: "Editor transformation session with multiple steps.",
    sortOrder: 370,
    visibleInCatalog: true,
    isFree: false,
  },
};

export function getPricingCatalogMeta(actionType: string): PricingCatalogActionMeta | null {
  return PRICING_CATALOG_ACTION_META[actionType] ?? null;
}

export function pricingCategoryLabelKey(category: PricingCatalogCategory): `pricing.catalog.category.${PricingCatalogCategory}` {
  return `pricing.catalog.category.${category}`;
}
