/**
 * S.8C margin input registry — machine-readable inventory from S.8B.
 * No margin math. Prices unchanged.
 */

export type S8CMarginInputRow = {
  actionType: string;
  displayCredits: number | "registry";
  resolvedCredits: "registry" | "overrideCredits" | "intent_map";
  provider: string;
  providerCapability: string;
  actualExecutionPath: string;
  jobWrapped: boolean;
  idempotent: boolean;
  cachePolicy: "none" | "CACHE_HIT_NO_CHARGE" | "TBD";
  subscriptionDiscountEligible: boolean;
  autoTopUpEligible: boolean;
  telemetryCoverage: "partial" | "mapped" | "missing";
  financialCorrelationCoverage: "partial" | "job" | "stripe" | "missing";
  pricesChangedInS8B: false;
};

export const S8C_MARGIN_INPUT_REGISTRY: S8CMarginInputRow[] = [
  {
    actionType: "scene_generation",
    displayCredits: "registry",
    resolvedCredits: "registry",
    provider: "openai",
    providerCapability: "IMAGE_GENERATE",
    actualExecutionPath: "storyboards/.../images → GenerationJob",
    jobWrapped: true,
    idempotent: true,
    cachePolicy: "none",
    subscriptionDiscountEligible: true,
    autoTopUpEligible: true,
    telemetryCoverage: "mapped",
    financialCorrelationCoverage: "job",
    pricesChangedInS8B: false,
  },
  {
    actionType: "voice_generation",
    displayCredits: "registry",
    resolvedCredits: "registry",
    provider: "elevenlabs",
    providerCapability: "VOICE_TTS",
    actualExecutionPath: "storyboards/.../voice → GenerationJob",
    jobWrapped: true,
    idempotent: true,
    cachePolicy: "none",
    subscriptionDiscountEligible: true,
    autoTopUpEligible: true,
    telemetryCoverage: "mapped",
    financialCorrelationCoverage: "job",
    pricesChangedInS8B: false,
  },
  {
    actionType: "voice_clone",
    displayCredits: 400,
    resolvedCredits: "registry",
    provider: "elevenlabs",
    providerCapability: "VOICE_CLONE",
    actualExecutionPath: "voice-clone routes → GenerationJob",
    jobWrapped: true,
    idempotent: true,
    cachePolicy: "none",
    subscriptionDiscountEligible: true,
    autoTopUpEligible: true,
    telemetryCoverage: "mapped",
    financialCorrelationCoverage: "job",
    pricesChangedInS8B: false,
  },
  {
    actionType: "music_generation",
    displayCredits: "registry",
    resolvedCredits: "registry",
    provider: "elevenlabs",
    providerCapability: "MUSIC_GENERATE",
    actualExecutionPath: "generate-music → GenerationJob",
    jobWrapped: true,
    idempotent: true,
    cachePolicy: "CACHE_HIT_NO_CHARGE",
    subscriptionDiscountEligible: true,
    autoTopUpEligible: true,
    telemetryCoverage: "mapped",
    financialCorrelationCoverage: "job",
    pricesChangedInS8B: false,
  },
  {
    actionType: "sfx_generation",
    displayCredits: "registry",
    resolvedCredits: "registry",
    provider: "elevenlabs",
    providerCapability: "SFX_GENERATE",
    actualExecutionPath: "generate-sfx → GenerationJob",
    jobWrapped: true,
    idempotent: true,
    cachePolicy: "CACHE_HIT_NO_CHARGE",
    subscriptionDiscountEligible: true,
    autoTopUpEligible: true,
    telemetryCoverage: "mapped",
    financialCorrelationCoverage: "job",
    pricesChangedInS8B: false,
  },
  {
    actionType: "subtitle_transcription",
    displayCredits: "registry",
    resolvedCredits: "registry",
    provider: "elevenlabs",
    providerCapability: "SUBTITLE_GENERATE",
    actualExecutionPath: "subtitles/transcribe → GenerationJob (S.8B)",
    jobWrapped: true,
    idempotent: true,
    cachePolicy: "TBD",
    subscriptionDiscountEligible: true,
    autoTopUpEligible: true,
    telemetryCoverage: "mapped",
    financialCorrelationCoverage: "job",
    pricesChangedInS8B: false,
  },
  {
    actionType: "translation_export",
    displayCredits: "registry",
    resolvedCredits: "registry",
    provider: "openai",
    providerCapability: "TRANSLATE",
    actualExecutionPath: "language-exports → GenerationJob (S.8B)",
    jobWrapped: true,
    idempotent: true,
    cachePolicy: "none",
    subscriptionDiscountEligible: true,
    autoTopUpEligible: true,
    telemetryCoverage: "mapped",
    financialCorrelationCoverage: "job",
    pricesChangedInS8B: false,
  },
  {
    actionType: "fusion_render",
    displayCredits: "registry",
    resolvedCredits: "intent_map",
    provider: "openai",
    providerCapability: "FUSION_RENDER",
    actualExecutionPath: "editor/fusion/render → GenerationJob",
    jobWrapped: true,
    idempotent: true,
    cachePolicy: "none",
    subscriptionDiscountEligible: true,
    autoTopUpEligible: true,
    telemetryCoverage: "mapped",
    financialCorrelationCoverage: "job",
    pricesChangedInS8B: false,
  },
  {
    actionType: "motion_render",
    displayCredits: "registry",
    resolvedCredits: "registry",
    provider: "vidu",
    providerCapability: "VIDEO_GENERATE",
    actualExecutionPath: "charge at project create; Job track-only",
    jobWrapped: true,
    idempotent: true,
    cachePolicy: "none",
    subscriptionDiscountEligible: true,
    autoTopUpEligible: true,
    telemetryCoverage: "partial",
    financialCorrelationCoverage: "partial",
    pricesChangedInS8B: false,
  },
  {
    actionType: "voice_suggestion",
    displayCredits: "registry",
    resolvedCredits: "registry",
    provider: "openai",
    providerCapability: "UNWIRED",
    actualExecutionPath: "registry only — UNWIRED",
    jobWrapped: false,
    idempotent: false,
    cachePolicy: "none",
    subscriptionDiscountEligible: false,
    autoTopUpEligible: false,
    telemetryCoverage: "missing",
    financialCorrelationCoverage: "missing",
    pricesChangedInS8B: false,
  },
];
