/**
 * S.6F — Product-level Creative Experience IDs (one family ownership each).
 * Maps onto S.6E Matrix experience IDs; does not duplicate Matrix engines.
 */

export const STUDIO_PRODUCT_EXPERIENCE_IDS = [
  // PEOPLE
  "PEOPLE_LINKEDIN_PHOTO",
  "PEOPLE_CV_PHOTO",
  "PEOPLE_BUSINESS_PORTRAIT",
  "PEOPLE_DATING_PROFILE",
  "PEOPLE_WEDDING",
  "PEOPLE_FAMILY",
  "PEOPLE_BABY",
  "PEOPLE_PREGNANCY",
  "PEOPLE_CHRISTMAS",
  "PEOPLE_BIRTHDAY",
  "PEOPLE_VACATION",
  "PEOPLE_RED_CARPET",
  "PEOPLE_CELEBRITY",
  "PEOPLE_GRADUATION",
  "PEOPLE_MEMORIAL",
  // BUSINESS
  "BUSINESS_RESTAURANT",
  "BUSINESS_HOMECHEFF",
  "BUSINESS_PRODUCT",
  "BUSINESS_REAL_ESTATE",
  "BUSINESS_AUTOMOTIVE",
  "BUSINESS_FASHION",
  "BUSINESS_RETAIL",
  "BUSINESS_CORPORATE",
  "BUSINESS_ADVERTISEMENT",
  "BUSINESS_COMMERCIAL",
  "BUSINESS_BRANDING",
  "BUSINESS_LOGO_PLACEMENT",
  "BUSINESS_COOKING_SHOW",
  // SOCIAL
  "SOCIAL_TIKTOK",
  "SOCIAL_INSTAGRAM",
  "SOCIAL_FACEBOOK",
  "SOCIAL_YOUTUBE",
  "SOCIAL_SHORTS",
  "SOCIAL_REELS",
  "SOCIAL_CAMPAIGN",
  // CREATIVE
  "CREATIVE_STORYBOARD",
  "CREATIVE_FILM",
  "CREATIVE_DOCUMENTARY",
  "CREATIVE_MUSIC_VIDEO",
  "CREATIVE_PODCAST",
  "CREATIVE_PRESENTATION",
  "CREATIVE_ANIMATION",
  "CREATIVE_TRAVEL_VLOG",
  "CREATIVE_EVENT_VIDEO",
  // IDENTITY
  "IDENTITY_OUTFIT",
  "IDENTITY_CHARACTER",
  "IDENTITY_MASCOT",
  "IDENTITY_FUTURE_CHILD",
  "IDENTITY_CHARACTER_FUSION",
  "IDENTITY_MOTION_READY",
  "IDENTITY_PERSON_BACKGROUND",
] as const;

export type StudioProductExperienceId = (typeof STUDIO_PRODUCT_EXPERIENCE_IDS)[number];

export function isStudioProductExperienceId(value: string): value is StudioProductExperienceId {
  return (STUDIO_PRODUCT_EXPERIENCE_IDS as readonly string[]).includes(value);
}
