/**
 * S.6F — Canonical product experience registry (single SoT for product experiences).
 * Each experience maps to one S.6E Matrix engine ID — no duplicate Matrix builders.
 */

import type { StudioCreativeExperienceId } from "@/lib/studio-prompt-matrix/experience-ids";
import type { StudioProductExperienceId } from "@/lib/studio-creative-director/product-experience-ids";
import type {
  StudioContinuityRequirementLevel,
  StudioDelegatedPlannerId,
  StudioProductExperienceFamily,
  StudioProductExperienceStatus,
  StudioProductMode,
} from "@/lib/studio-creative-director/types";

export type StudioProductExperienceEntry = {
  experienceId: StudioProductExperienceId;
  family: StudioProductExperienceFamily;
  label: string;
  creativeGoal: string;
  status: StudioProductExperienceStatus;
  /** S.6E Matrix engine — never a second prompt stack */
  matrixExperienceId: StudioCreativeExperienceId;
  supportedModes: StudioProductMode[];
  requiredAssets: string[];
  optionalAssets: string[];
  recommendedPlanners: StudioDelegatedPlannerId[];
  continuityRequirements: StudioContinuityRequirementLevel;
  generationStrategy: string;
  providerCapabilities: string[];
  /** Entry fans that resolve to this experience (no duplicate ownership) */
  entryFans: string[];
  quickQuestions: string[];
};

const ALL_MODES: StudioProductMode[] = ["QUICK", "PROFESSIONAL", "DIRECTOR"];
const QP: StudioProductMode[] = ["QUICK", "PROFESSIONAL"];
const QPD = ALL_MODES;

function entry(
  partial: StudioProductExperienceEntry
): StudioProductExperienceEntry {
  return partial;
}

export const STUDIO_PRODUCT_EXPERIENCE_REGISTRY: Record<
  StudioProductExperienceId,
  StudioProductExperienceEntry
> = {
  PEOPLE_LINKEDIN_PHOTO: entry({
    experienceId: "PEOPLE_LINKEDIN_PHOTO",
    family: "PEOPLE",
    label: "LinkedIn photo",
    creativeGoal: "professional_headshot_social",
    status: "PARTIAL",
    matrixExperienceId: "PERSON_BACKGROUND",
    supportedModes: QP,
    requiredAssets: ["source_image"],
    optionalAssets: ["character"],
    recommendedPlanners: ["fusion_intelligence", "creation_assistant"],
    continuityRequirements: "fusion_refs",
    generationStrategy: "fusion_or_instant_still",
    providerCapabilities: ["openai_image"],
    entryFans: ["linkedin_photo", "linkedin_export"],
    quickQuestions: ["business_style", "background", "smile", "attire"],
  }),
  PEOPLE_CV_PHOTO: entry({
    experienceId: "PEOPLE_CV_PHOTO",
    family: "PEOPLE",
    label: "CV photo",
    creativeGoal: "cv_portrait",
    status: "PARTIAL",
    matrixExperienceId: "PERSON_BACKGROUND",
    supportedModes: QP,
    requiredAssets: ["source_image"],
    optionalAssets: ["character"],
    recommendedPlanners: ["fusion_intelligence"],
    continuityRequirements: "fusion_refs",
    generationStrategy: "fusion_or_instant_still",
    providerCapabilities: ["openai_image"],
    entryFans: ["cv_photo"],
    quickQuestions: ["formal_level", "background", "expression"],
  }),
  PEOPLE_BUSINESS_PORTRAIT: entry({
    experienceId: "PEOPLE_BUSINESS_PORTRAIT",
    family: "PEOPLE",
    label: "Business portrait",
    creativeGoal: "business_portrait",
    status: "PARTIAL",
    matrixExperienceId: "PERSON_BACKGROUND",
    supportedModes: QPD,
    requiredAssets: ["source_image"],
    optionalAssets: ["character", "location"],
    recommendedPlanners: ["fusion_intelligence", "scene_still_matrix"],
    continuityRequirements: "when_linked",
    generationStrategy: "fusion_or_scene_still",
    providerCapabilities: ["openai_image"],
    entryFans: ["clean_business", "business_portrait"],
    quickQuestions: ["style", "background", "branding"],
  }),
  PEOPLE_DATING_PROFILE: entry({
    experienceId: "PEOPLE_DATING_PROFILE",
    family: "PEOPLE",
    label: "Dating profile",
    creativeGoal: "dating_portrait",
    status: "MISSING",
    matrixExperienceId: "LEGACY_UNMAPPED",
    supportedModes: ["QUICK"],
    requiredAssets: ["source_image"],
    optionalAssets: [],
    recommendedPlanners: ["creation_assistant"],
    continuityRequirements: "source_image",
    generationStrategy: "unimplemented_pack",
    providerCapabilities: [],
    entryFans: [],
    quickQuestions: ["vibe", "outdoor_indoor", "smile"],
  }),
  PEOPLE_WEDDING: entry({
    experienceId: "PEOPLE_WEDDING",
    family: "PEOPLE",
    label: "Wedding",
    creativeGoal: "wedding_moment",
    status: "PARTIAL",
    matrixExperienceId: "VIDEO_INTENT",
    supportedModes: QP,
    requiredAssets: ["source_image"],
    optionalAssets: ["character", "location"],
    recommendedPlanners: ["animation_planner", "vidu_execution_planner"],
    continuityRequirements: "source_image",
    generationStrategy: "motion_preset_or_event_intent",
    providerCapabilities: ["vidu_motion"],
    entryFans: ["wedding_entrance", "wedding"],
    quickQuestions: ["moment", "mood", "music"],
  }),
  PEOPLE_FAMILY: entry({
    experienceId: "PEOPLE_FAMILY",
    family: "PEOPLE",
    label: "Family",
    creativeGoal: "family_group",
    status: "PARTIAL",
    matrixExperienceId: "MOTION_PRESET",
    supportedModes: QP,
    requiredAssets: ["source_image"],
    optionalAssets: ["character"],
    recommendedPlanners: ["animation_planner", "fusion_intelligence"],
    continuityRequirements: "fusion_refs",
    generationStrategy: "group_photo_or_fusion",
    providerCapabilities: ["vidu_motion", "openai_image"],
    entryFans: ["group_photo", "family_photo"],
    quickQuestions: ["group_size", "style", "occasion"],
  }),
  PEOPLE_BABY: entry({
    experienceId: "PEOPLE_BABY",
    family: "PEOPLE",
    label: "Baby",
    creativeGoal: "baby_moment",
    status: "MISSING",
    matrixExperienceId: "FUSION_EXPERIMENTAL",
    supportedModes: ["QUICK"],
    requiredAssets: ["source_image"],
    optionalAssets: [],
    recommendedPlanners: [],
    continuityRequirements: "fusion_refs",
    generationStrategy: "unimplemented_pack",
    providerCapabilities: [],
    entryFans: ["future_child_age_baby"],
    quickQuestions: ["style", "softness"],
  }),
  PEOPLE_PREGNANCY: entry({
    experienceId: "PEOPLE_PREGNANCY",
    family: "PEOPLE",
    label: "Pregnancy",
    creativeGoal: "pregnancy_portrait",
    status: "MISSING",
    matrixExperienceId: "LEGACY_UNMAPPED",
    supportedModes: ["QUICK"],
    requiredAssets: ["source_image"],
    optionalAssets: [],
    recommendedPlanners: [],
    continuityRequirements: "source_image",
    generationStrategy: "unimplemented_pack",
    providerCapabilities: [],
    entryFans: [],
    quickQuestions: ["style", "setting"],
  }),
  PEOPLE_CHRISTMAS: entry({
    experienceId: "PEOPLE_CHRISTMAS",
    family: "PEOPLE",
    label: "Christmas",
    creativeGoal: "holiday_moment",
    status: "MISSING",
    matrixExperienceId: "LEGACY_UNMAPPED",
    supportedModes: ["QUICK"],
    requiredAssets: ["source_image"],
    optionalAssets: [],
    recommendedPlanners: [],
    continuityRequirements: "source_image",
    generationStrategy: "unimplemented_pack",
    providerCapabilities: [],
    entryFans: [],
    quickQuestions: ["family_or_solo", "style"],
  }),
  PEOPLE_BIRTHDAY: entry({
    experienceId: "PEOPLE_BIRTHDAY",
    family: "PEOPLE",
    label: "Birthday",
    creativeGoal: "birthday_celebration",
    status: "PARTIAL",
    matrixExperienceId: "MOTION_PRESET",
    supportedModes: QP,
    requiredAssets: ["source_image"],
    optionalAssets: [],
    recommendedPlanners: ["animation_planner"],
    continuityRequirements: "source_image",
    generationStrategy: "motion_preset",
    providerCapabilities: ["vidu_motion"],
    entryFans: ["birthday_celebration"],
    quickQuestions: ["energy", "age_group"],
  }),
  PEOPLE_VACATION: entry({
    experienceId: "PEOPLE_VACATION",
    family: "PEOPLE",
    label: "Vacation",
    creativeGoal: "vacation_travel",
    status: "PARTIAL",
    matrixExperienceId: "VIDEO_INTENT",
    supportedModes: QP,
    requiredAssets: ["source_image"],
    optionalAssets: ["location"],
    recommendedPlanners: ["animation_planner", "ai_director_interpreter"],
    continuityRequirements: "when_linked",
    generationStrategy: "travel_vlog_or_preset",
    providerCapabilities: ["vidu_motion"],
    entryFans: ["vacation", "airport_arrival"],
    quickQuestions: ["destination_vibe", "pace"],
  }),
  PEOPLE_RED_CARPET: entry({
    experienceId: "PEOPLE_RED_CARPET",
    family: "PEOPLE",
    label: "Red carpet",
    creativeGoal: "red_carpet_moment",
    status: "PARTIAL",
    matrixExperienceId: "MOTION_PRESET",
    supportedModes: QP,
    requiredAssets: ["source_image"],
    optionalAssets: ["character"],
    recommendedPlanners: ["animation_planner", "fusion_intelligence"],
    continuityRequirements: "source_image",
    generationStrategy: "luxury_or_fashion_preset",
    providerCapabilities: ["vidu_motion", "openai_image"],
    entryFans: ["luxury_entrance", "red_carpet"],
    quickQuestions: ["glamour", "outfit"],
  }),
  PEOPLE_CELEBRITY: entry({
    experienceId: "PEOPLE_CELEBRITY",
    family: "PEOPLE",
    label: "Celebrity look",
    creativeGoal: "celebrity_style",
    status: "EXPERIMENTAL",
    matrixExperienceId: "FUSION_EXPERIMENTAL",
    supportedModes: ["QUICK", "PROFESSIONAL"],
    requiredAssets: ["source_image"],
    optionalAssets: [],
    recommendedPlanners: ["fusion_intelligence"],
    continuityRequirements: "fusion_refs",
    generationStrategy: "fusion_sim",
    providerCapabilities: ["openai_image"],
    entryFans: ["how_will_i_look"],
    quickQuestions: ["style_era"],
  }),
  PEOPLE_GRADUATION: entry({
    experienceId: "PEOPLE_GRADUATION",
    family: "PEOPLE",
    label: "Graduation",
    creativeGoal: "graduation_moment",
    status: "PARTIAL",
    matrixExperienceId: "MOTION_PRESET",
    supportedModes: QP,
    requiredAssets: ["source_image"],
    optionalAssets: [],
    recommendedPlanners: ["animation_planner"],
    continuityRequirements: "source_image",
    generationStrategy: "motion_preset",
    providerCapabilities: ["vidu_motion"],
    entryFans: ["graduation_moment"],
    quickQuestions: ["mood", "group_or_solo"],
  }),
  PEOPLE_MEMORIAL: entry({
    experienceId: "PEOPLE_MEMORIAL",
    family: "PEOPLE",
    label: "Memorial",
    creativeGoal: "memorial_tribute",
    status: "MISSING",
    matrixExperienceId: "LEGACY_UNMAPPED",
    supportedModes: ["QUICK"],
    requiredAssets: ["source_image"],
    optionalAssets: [],
    recommendedPlanners: [],
    continuityRequirements: "source_image",
    generationStrategy: "unimplemented_pack",
    providerCapabilities: [],
    entryFans: [],
    quickQuestions: ["tone", "music"],
  }),

  BUSINESS_RESTAURANT: entry({
    experienceId: "BUSINESS_RESTAURANT",
    family: "BUSINESS",
    label: "Restaurant",
    creativeGoal: "restaurant_promo",
    status: "LIVE",
    matrixExperienceId: "RESTAURANT_PROMO",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["character", "location", "prop", "brand"],
    recommendedPlanners: ["ai_director_interpreter", "auto_shot", "music_director", "scene_still_matrix"],
    continuityRequirements: "when_linked",
    generationStrategy: "video_intent_then_motion",
    providerCapabilities: ["openai_image", "vidu_motion"],
    entryFans: ["restaurant_promo", "restaurant_service"],
    quickQuestions: ["logo", "brand_colors", "audience", "platform", "commercial_tone"],
  }),
  BUSINESS_HOMECHEFF: entry({
    experienceId: "BUSINESS_HOMECHEFF",
    family: "BUSINESS",
    label: "HomeCheff",
    creativeGoal: "homecheff_food_brand",
    status: "LIVE",
    matrixExperienceId: "FOOD_PROMO",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["character", "location", "prop", "world", "brand"],
    recommendedPlanners: ["scene_still_matrix", "animation_planner", "music_director"],
    continuityRequirements: "when_linked",
    generationStrategy: "food_promo_or_cooking",
    providerCapabilities: ["openai_image", "vidu_motion"],
    entryFans: ["food_promo", "homecheff"],
    quickQuestions: ["dish", "appetite", "platform"],
  }),
  BUSINESS_PRODUCT: entry({
    experienceId: "BUSINESS_PRODUCT",
    family: "BUSINESS",
    label: "Product",
    creativeGoal: "product_showcase",
    status: "LIVE",
    matrixExperienceId: "PRODUCT_BRANDING",
    supportedModes: QPD,
    requiredAssets: ["source_image"],
    optionalAssets: ["prop", "brand"],
    recommendedPlanners: ["fusion_intelligence", "ai_director_interpreter"],
    continuityRequirements: "fusion_refs",
    generationStrategy: "fusion_or_video_intent",
    providerCapabilities: ["openai_image", "vidu_motion"],
    entryFans: ["product_branding", "product_packaging", "product_family"],
    quickQuestions: ["hero_angle", "branding", "platform"],
  }),
  BUSINESS_REAL_ESTATE: entry({
    experienceId: "BUSINESS_REAL_ESTATE",
    family: "BUSINESS",
    label: "Real estate",
    creativeGoal: "real_estate_showcase",
    status: "MISSING",
    matrixExperienceId: "LEGACY_UNMAPPED",
    supportedModes: ["QUICK", "PROFESSIONAL"],
    requiredAssets: ["source_image"],
    optionalAssets: ["location"],
    recommendedPlanners: ["creation_assistant"],
    continuityRequirements: "source_image",
    generationStrategy: "unimplemented_pack",
    providerCapabilities: [],
    entryFans: ["future_home_seo"],
    quickQuestions: ["interior_exterior", "luxury_level"],
  }),
  BUSINESS_AUTOMOTIVE: entry({
    experienceId: "BUSINESS_AUTOMOTIVE",
    family: "BUSINESS",
    label: "Automotive",
    creativeGoal: "automotive_showcase",
    status: "PARTIAL",
    matrixExperienceId: "MOTION_PRESET",
    supportedModes: QP,
    requiredAssets: ["source_image"],
    optionalAssets: ["prop"],
    recommendedPlanners: ["animation_planner"],
    continuityRequirements: "source_image",
    generationStrategy: "motion_preset",
    providerCapabilities: ["vidu_motion"],
    entryFans: ["sports_car_arrival"],
    quickQuestions: ["energy", "reveal"],
  }),
  BUSINESS_FASHION: entry({
    experienceId: "BUSINESS_FASHION",
    family: "BUSINESS",
    label: "Fashion",
    creativeGoal: "fashion_reel",
    status: "LIVE",
    matrixExperienceId: "FASHION_REEL",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["character", "prop"],
    recommendedPlanners: ["auto_shot", "animation_planner", "fusion_intelligence"],
    continuityRequirements: "when_linked",
    generationStrategy: "fashion_reel_or_outfit",
    providerCapabilities: ["openai_image", "vidu_motion"],
    entryFans: ["fashion_reel", "fashion_runway"],
    quickQuestions: ["runway_or_lookbook", "platform"],
  }),
  BUSINESS_RETAIL: entry({
    experienceId: "BUSINESS_RETAIL",
    family: "BUSINESS",
    label: "Retail",
    creativeGoal: "retail_promo",
    status: "PARTIAL",
    matrixExperienceId: "VIDEO_INTENT",
    supportedModes: QP,
    requiredAssets: [],
    optionalAssets: ["prop", "location", "brand"],
    recommendedPlanners: ["ai_director_interpreter", "music_director"],
    continuityRequirements: "when_linked",
    generationStrategy: "product_commercial_adjacent",
    providerCapabilities: ["vidu_motion", "openai_image"],
    entryFans: ["retail_promo"],
    quickQuestions: ["offer", "platform"],
  }),
  BUSINESS_CORPORATE: entry({
    experienceId: "BUSINESS_CORPORATE",
    family: "BUSINESS",
    label: "Corporate",
    creativeGoal: "corporate_video",
    status: "LIVE",
    matrixExperienceId: "VIDEO_INTENT",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["character", "location", "brand"],
    recommendedPlanners: ["ai_director_interpreter", "auto_shot", "voice_director"],
    continuityRequirements: "when_linked",
    generationStrategy: "company_or_presentation_intent",
    providerCapabilities: ["openai_image", "vidu_motion", "elevenlabs_tts"],
    entryFans: ["company_video"],
    quickQuestions: ["audience", "tone", "duration"],
  }),
  BUSINESS_ADVERTISEMENT: entry({
    experienceId: "BUSINESS_ADVERTISEMENT",
    family: "BUSINESS",
    label: "Advertisement",
    creativeGoal: "advertisement",
    status: "PARTIAL",
    matrixExperienceId: "PRODUCT_BRANDING",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["brand", "prop", "character"],
    recommendedPlanners: ["fusion_intelligence", "director_proposal"],
    continuityRequirements: "when_linked",
    generationStrategy: "fusion_ad_or_campaign",
    providerCapabilities: ["openai_image", "vidu_motion"],
    entryFans: ["ad_composition", "campaign_variant"],
    quickQuestions: ["hook", "cta", "platform"],
  }),
  BUSINESS_COMMERCIAL: entry({
    experienceId: "BUSINESS_COMMERCIAL",
    family: "BUSINESS",
    label: "Commercial",
    creativeGoal: "product_commercial",
    status: "LIVE",
    matrixExperienceId: "VIDEO_INTENT",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["character", "prop", "location", "brand"],
    recommendedPlanners: ["director_proposal", "auto_shot", "music_director", "production_center"],
    continuityRequirements: "when_linked",
    generationStrategy: "product_commercial_intent",
    providerCapabilities: ["openai_image", "vidu_motion"],
    entryFans: ["product_commercial"],
    quickQuestions: ["product", "audience", "duration"],
  }),
  BUSINESS_BRANDING: entry({
    experienceId: "BUSINESS_BRANDING",
    family: "BUSINESS",
    label: "Branding",
    creativeGoal: "brand_identity_visual",
    status: "LIVE",
    matrixExperienceId: "PRODUCT_BRANDING",
    supportedModes: QPD,
    requiredAssets: ["source_image"],
    optionalAssets: ["brand"],
    recommendedPlanners: ["fusion_intelligence"],
    continuityRequirements: "fusion_refs",
    generationStrategy: "product_branding_fusion",
    providerCapabilities: ["openai_image"],
    entryFans: ["brand_story", "branding"],
    quickQuestions: ["logo", "colors", "message"],
  }),
  BUSINESS_LOGO_PLACEMENT: entry({
    experienceId: "BUSINESS_LOGO_PLACEMENT",
    family: "BUSINESS",
    label: "Logo placement",
    creativeGoal: "logo_placement",
    status: "LIVE",
    matrixExperienceId: "PRODUCT_BRANDING",
    supportedModes: QPD,
    requiredAssets: ["source_image", "logo"],
    optionalAssets: ["brand"],
    recommendedPlanners: ["fusion_intelligence"],
    continuityRequirements: "fusion_refs",
    generationStrategy: "logo_wizard_fusion",
    providerCapabilities: ["openai_image"],
    entryFans: ["logo_placement"],
    quickQuestions: ["placement", "scale", "preserve_subject"],
  }),
  BUSINESS_COOKING_SHOW: entry({
    experienceId: "BUSINESS_COOKING_SHOW",
    family: "BUSINESS",
    label: "Cooking show",
    creativeGoal: "cooking_show",
    status: "LIVE",
    matrixExperienceId: "COOKING_SHOW",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["character", "location", "prop", "world"],
    recommendedPlanners: ["auto_shot", "music_director", "scene_still_matrix"],
    continuityRequirements: "when_linked",
    generationStrategy: "cooking_show_intent",
    providerCapabilities: ["openai_image", "vidu_motion"],
    entryFans: ["cooking_show", "cooking_tutorial"],
    quickQuestions: ["dish", "host", "duration"],
  }),

  SOCIAL_TIKTOK: entry({
    experienceId: "SOCIAL_TIKTOK",
    family: "SOCIAL",
    label: "TikTok",
    creativeGoal: "tiktok_short",
    status: "LIVE",
    matrixExperienceId: "SOCIAL_CAMPAIGN",
    supportedModes: QP,
    requiredAssets: [],
    optionalAssets: ["source_image", "character"],
    recommendedPlanners: ["animation_planner", "music_director"],
    continuityRequirements: "when_linked",
    generationStrategy: "social_campaign_9_16",
    providerCapabilities: ["vidu_motion"],
    entryFans: ["tiktok_trend", "tiktok"],
    quickQuestions: ["hook", "energy", "duration"],
  }),
  SOCIAL_INSTAGRAM: entry({
    experienceId: "SOCIAL_INSTAGRAM",
    family: "SOCIAL",
    label: "Instagram",
    creativeGoal: "instagram_content",
    status: "LIVE",
    matrixExperienceId: "SOCIAL_CAMPAIGN",
    supportedModes: QP,
    requiredAssets: [],
    optionalAssets: ["source_image", "character"],
    recommendedPlanners: ["animation_planner", "music_director"],
    continuityRequirements: "when_linked",
    generationStrategy: "social_campaign_9_16",
    providerCapabilities: ["vidu_motion", "openai_image"],
    entryFans: ["instagram", "instagram_post"],
    quickQuestions: ["reel_or_post", "energy"],
  }),
  SOCIAL_FACEBOOK: entry({
    experienceId: "SOCIAL_FACEBOOK",
    family: "SOCIAL",
    label: "Facebook",
    creativeGoal: "facebook_social",
    status: "PARTIAL",
    matrixExperienceId: "SOCIAL_CAMPAIGN",
    supportedModes: QP,
    requiredAssets: [],
    optionalAssets: ["source_image"],
    recommendedPlanners: ["ai_director_interpreter"],
    continuityRequirements: "when_linked",
    generationStrategy: "social_campaign",
    providerCapabilities: ["vidu_motion"],
    entryFans: ["facebook"],
    quickQuestions: ["audience", "tone"],
  }),
  SOCIAL_YOUTUBE: entry({
    experienceId: "SOCIAL_YOUTUBE",
    family: "SOCIAL",
    label: "YouTube",
    creativeGoal: "youtube_video",
    status: "PARTIAL",
    matrixExperienceId: "VIDEO_INTENT",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["character", "location"],
    recommendedPlanners: ["director_proposal", "ai_director_interpreter", "production_center"],
    continuityRequirements: "when_linked",
    generationStrategy: "long_form_or_intent",
    providerCapabilities: ["vidu_motion", "openai_image"],
    entryFans: ["youtube"],
    quickQuestions: ["length", "topic"],
  }),
  SOCIAL_SHORTS: entry({
    experienceId: "SOCIAL_SHORTS",
    family: "SOCIAL",
    label: "YouTube Shorts",
    creativeGoal: "youtube_shorts",
    status: "LIVE",
    matrixExperienceId: "SOCIAL_CAMPAIGN",
    supportedModes: QP,
    requiredAssets: [],
    optionalAssets: ["source_image"],
    recommendedPlanners: ["animation_planner"],
    continuityRequirements: "source_image",
    generationStrategy: "short_form_9_16",
    providerCapabilities: ["vidu_motion"],
    entryFans: ["youtube_shorts", "social_boost"],
    quickQuestions: ["hook", "duration"],
  }),
  SOCIAL_REELS: entry({
    experienceId: "SOCIAL_REELS",
    family: "SOCIAL",
    label: "Instagram Reels",
    creativeGoal: "instagram_reels",
    status: "LIVE",
    matrixExperienceId: "SOCIAL_CAMPAIGN",
    supportedModes: QP,
    requiredAssets: [],
    optionalAssets: ["source_image", "character"],
    recommendedPlanners: ["animation_planner", "music_director"],
    continuityRequirements: "when_linked",
    generationStrategy: "short_form_9_16",
    providerCapabilities: ["vidu_motion"],
    entryFans: ["influencer_reel", "instagram_reels"],
    quickQuestions: ["energy", "music"],
  }),
  SOCIAL_CAMPAIGN: entry({
    experienceId: "SOCIAL_CAMPAIGN",
    family: "SOCIAL",
    label: "Social campaign",
    creativeGoal: "social_campaign",
    status: "LIVE",
    matrixExperienceId: "SOCIAL_CAMPAIGN",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["character", "brand", "location"],
    recommendedPlanners: ["director_proposal", "auto_shot", "music_director"],
    continuityRequirements: "when_linked",
    generationStrategy: "social_campaign_intent",
    providerCapabilities: ["openai_image", "vidu_motion"],
    entryFans: ["social_campaign"],
    quickQuestions: ["platforms", "message", "duration"],
  }),

  CREATIVE_STORYBOARD: entry({
    experienceId: "CREATIVE_STORYBOARD",
    family: "CREATIVE",
    label: "Storyboard",
    creativeGoal: "multi_scene_storyboard",
    status: "LIVE",
    matrixExperienceId: "SCENE_STILL",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["character", "location", "prop", "world"],
    recommendedPlanners: [
      "director_proposal",
      "auto_shot",
      "scene_still_matrix",
      "creation_assistant",
    ],
    continuityRequirements: "when_linked",
    generationStrategy: "scene_stills_then_motion",
    providerCapabilities: ["openai_image", "vidu_motion"],
    entryFans: ["studio_workspace", "IMAGE_GENERATE"],
    quickQuestions: ["idea", "scene_count", "style"],
  }),
  CREATIVE_FILM: entry({
    experienceId: "CREATIVE_FILM",
    family: "CREATIVE",
    label: "Film",
    creativeGoal: "short_film",
    status: "ADVANCED",
    matrixExperienceId: "SCENE_STILL",
    supportedModes: ["PROFESSIONAL", "DIRECTOR"],
    requiredAssets: [],
    optionalAssets: ["character", "location", "prop", "world"],
    recommendedPlanners: ["movie_builder", "production_center", "director_proposal", "auto_shot"],
    continuityRequirements: "when_linked",
    generationStrategy: "movie_builder_pipeline",
    providerCapabilities: ["openai_image", "vidu_motion"],
    entryFans: ["movie_builder"],
    quickQuestions: ["genre", "length", "tone"],
  }),
  CREATIVE_DOCUMENTARY: entry({
    experienceId: "CREATIVE_DOCUMENTARY",
    family: "CREATIVE",
    label: "Documentary",
    creativeGoal: "documentary",
    status: "LIVE",
    matrixExperienceId: "VIDEO_INTENT",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["character", "location"],
    recommendedPlanners: ["ai_director_interpreter", "voice_director", "auto_shot"],
    continuityRequirements: "when_linked",
    generationStrategy: "documentary_intent",
    providerCapabilities: ["openai_image", "vidu_motion", "elevenlabs_tts"],
    entryFans: ["documentary"],
    quickQuestions: ["subject", "tone", "narration"],
  }),
  CREATIVE_MUSIC_VIDEO: entry({
    experienceId: "CREATIVE_MUSIC_VIDEO",
    family: "CREATIVE",
    label: "Music video",
    creativeGoal: "music_video",
    status: "LIVE",
    matrixExperienceId: "VIDEO_INTENT",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["character", "location", "source_image"],
    recommendedPlanners: ["music_director", "auto_shot", "animation_planner"],
    continuityRequirements: "when_linked",
    generationStrategy: "music_video_intent",
    providerCapabilities: ["vidu_motion", "openai_image"],
    entryFans: ["music_video"],
    quickQuestions: ["genre", "energy", "duration"],
  }),
  CREATIVE_PODCAST: entry({
    experienceId: "CREATIVE_PODCAST",
    family: "CREATIVE",
    label: "Podcast",
    creativeGoal: "podcast_clip",
    status: "LIVE",
    matrixExperienceId: "VIDEO_INTENT",
    supportedModes: QP,
    requiredAssets: [],
    optionalAssets: ["character", "source_image"],
    recommendedPlanners: ["voice_director", "animation_planner"],
    continuityRequirements: "when_linked",
    generationStrategy: "podcast_video_intent",
    providerCapabilities: ["vidu_motion", "elevenlabs_tts"],
    entryFans: ["podcast_video", "podcast_clip"],
    quickQuestions: ["talking_head", "captions"],
  }),
  CREATIVE_PRESENTATION: entry({
    experienceId: "CREATIVE_PRESENTATION",
    family: "CREATIVE",
    label: "Presentation",
    creativeGoal: "presentation_video",
    status: "LIVE",
    matrixExperienceId: "VIDEO_INTENT",
    supportedModes: QPD,
    requiredAssets: [],
    optionalAssets: ["character", "brand"],
    recommendedPlanners: ["voice_director", "ai_director_interpreter"],
    continuityRequirements: "when_linked",
    generationStrategy: "presentation_intent",
    providerCapabilities: ["vidu_motion", "elevenlabs_tts", "openai_image"],
    entryFans: ["presentation_video", "business_presentation", "startup_pitch"],
    quickQuestions: ["audience", "slides_or_talking_head"],
  }),
  CREATIVE_ANIMATION: entry({
    experienceId: "CREATIVE_ANIMATION",
    family: "CREATIVE",
    label: "Animation",
    creativeGoal: "photo_to_animation",
    status: "LIVE",
    matrixExperienceId: "INSTANT_PHOTO_TO_VIDEO",
    supportedModes: QP,
    requiredAssets: ["source_image"],
    optionalAssets: [],
    recommendedPlanners: ["animation_planner", "vidu_execution_planner"],
    continuityRequirements: "source_image",
    generationStrategy: "instant_photo_to_video",
    providerCapabilities: ["vidu_motion"],
    entryFans: ["animate_photo", "bring_photo_to_life", "photo_to_video"],
    quickQuestions: ["motion_style", "duration"],
  }),
  CREATIVE_TRAVEL_VLOG: entry({
    experienceId: "CREATIVE_TRAVEL_VLOG",
    family: "CREATIVE",
    label: "Travel vlog",
    creativeGoal: "travel_vlog",
    status: "LIVE",
    matrixExperienceId: "VIDEO_INTENT",
    supportedModes: QP,
    requiredAssets: [],
    optionalAssets: ["location", "character", "source_image"],
    recommendedPlanners: ["ai_director_interpreter", "animation_planner"],
    continuityRequirements: "when_linked",
    generationStrategy: "travel_vlog_intent",
    providerCapabilities: ["vidu_motion", "openai_image"],
    entryFans: ["travel_vlog"],
    quickQuestions: ["destination", "pace"],
  }),
  CREATIVE_EVENT_VIDEO: entry({
    experienceId: "CREATIVE_EVENT_VIDEO",
    family: "CREATIVE",
    label: "Event video",
    creativeGoal: "event_video",
    status: "LIVE",
    matrixExperienceId: "VIDEO_INTENT",
    supportedModes: QP,
    requiredAssets: [],
    optionalAssets: ["source_image", "character"],
    recommendedPlanners: ["ai_director_interpreter", "music_director"],
    continuityRequirements: "when_linked",
    generationStrategy: "event_video_intent",
    providerCapabilities: ["vidu_motion"],
    entryFans: ["event_video"],
    quickQuestions: ["event_type", "highlights"],
  }),

  IDENTITY_OUTFIT: entry({
    experienceId: "IDENTITY_OUTFIT",
    family: "IDENTITY",
    label: "Outfit change",
    creativeGoal: "outfit_change",
    status: "LIVE",
    matrixExperienceId: "OUTFIT_CHANGE",
    supportedModes: QPD,
    requiredAssets: ["source_image", "outfit_reference"],
    optionalAssets: ["character"],
    recommendedPlanners: ["fusion_intelligence"],
    continuityRequirements: "fusion_refs",
    generationStrategy: "fusion_outfit",
    providerCapabilities: ["openai_image"],
    entryFans: ["outfit_from_reference", "person_outfit", "character_studio_outfit"],
    quickQuestions: ["outfit_style", "preserve_face"],
  }),
  IDENTITY_CHARACTER: entry({
    experienceId: "IDENTITY_CHARACTER",
    family: "IDENTITY",
    label: "Character",
    creativeGoal: "character_identity",
    status: "LIVE",
    matrixExperienceId: "SCENE_STILL",
    supportedModes: QPD,
    requiredAssets: ["character"],
    optionalAssets: ["location", "prop", "world"],
    recommendedPlanners: ["scene_still_matrix", "creation_assistant"],
    continuityRequirements: "required_entities",
    generationStrategy: "character_linked_scene_still",
    providerCapabilities: ["openai_image"],
    entryFans: ["studio_characters", "character_upgrade"],
    quickQuestions: ["role", "look"],
  }),
  IDENTITY_MASCOT: entry({
    experienceId: "IDENTITY_MASCOT",
    family: "IDENTITY",
    label: "Mascot",
    creativeGoal: "mascot_transform",
    status: "LIVE",
    matrixExperienceId: "CHARACTER_FUSION",
    supportedModes: QPD,
    requiredAssets: ["source_image"],
    optionalAssets: ["character"],
    recommendedPlanners: ["fusion_intelligence", "animation_planner"],
    continuityRequirements: "fusion_refs",
    generationStrategy: "mascot_fusion",
    providerCapabilities: ["openai_image", "vidu_motion"],
    entryFans: ["human_into_mascot", "mascot_into_human", "mascot_transform", "mascot_introduction"],
    quickQuestions: ["mascot_style", "motion"],
  }),
  IDENTITY_FUTURE_CHILD: entry({
    experienceId: "IDENTITY_FUTURE_CHILD",
    family: "IDENTITY",
    label: "Future child",
    creativeGoal: "future_child_sim",
    status: "EXPERIMENTAL",
    matrixExperienceId: "FUSION_EXPERIMENTAL",
    supportedModes: ["PROFESSIONAL", "DIRECTOR"],
    requiredAssets: ["source_image"],
    optionalAssets: [],
    recommendedPlanners: ["fusion_intelligence"],
    continuityRequirements: "fusion_refs",
    generationStrategy: "fusion_sim",
    providerCapabilities: ["openai_image"],
    entryFans: ["future_child", "genetic_blend"],
    quickQuestions: ["age", "traits"],
  }),
  IDENTITY_CHARACTER_FUSION: entry({
    experienceId: "IDENTITY_CHARACTER_FUSION",
    family: "IDENTITY",
    label: "Character fusion",
    creativeGoal: "character_fusion",
    status: "LIVE",
    matrixExperienceId: "CHARACTER_FUSION",
    supportedModes: QPD,
    requiredAssets: ["source_image"],
    optionalAssets: ["character"],
    recommendedPlanners: ["fusion_intelligence"],
    continuityRequirements: "fusion_refs",
    generationStrategy: "character_fusion",
    providerCapabilities: ["openai_image"],
    entryFans: ["character_fusion"],
    quickQuestions: ["blend_strength", "preserve_identity"],
  }),
  IDENTITY_MOTION_READY: entry({
    experienceId: "IDENTITY_MOTION_READY",
    family: "IDENTITY",
    label: "Motion ready",
    creativeGoal: "motion_ready_character",
    status: "LIVE",
    matrixExperienceId: "STUDIO_MOTION_HANDOFF",
    supportedModes: QPD,
    requiredAssets: ["character"],
    optionalAssets: ["source_image"],
    recommendedPlanners: ["animation_planner", "vidu_execution_planner"],
    continuityRequirements: "when_linked",
    generationStrategy: "character_prep_then_motion",
    providerCapabilities: ["openai_image", "vidu_motion"],
    entryFans: ["motion_ready", "full_body"],
    quickQuestions: ["motion_style"],
  }),
  IDENTITY_PERSON_BACKGROUND: entry({
    experienceId: "IDENTITY_PERSON_BACKGROUND",
    family: "IDENTITY",
    label: "Person background",
    creativeGoal: "person_background_swap",
    status: "LIVE",
    matrixExperienceId: "PERSON_BACKGROUND",
    supportedModes: QPD,
    requiredAssets: ["source_image"],
    optionalAssets: ["location", "character"],
    recommendedPlanners: ["fusion_intelligence"],
    continuityRequirements: "fusion_refs",
    generationStrategy: "person_background_fusion",
    providerCapabilities: ["openai_image"],
    entryFans: ["person_background"],
    quickQuestions: ["background_type", "preserve_subject"],
  }),
};

export function getProductExperience(
  experienceId: StudioProductExperienceId
): StudioProductExperienceEntry {
  return STUDIO_PRODUCT_EXPERIENCE_REGISTRY[experienceId];
}

export function listProductExperiencesByFamily(
  family: StudioProductExperienceFamily
): StudioProductExperienceEntry[] {
  return Object.values(STUDIO_PRODUCT_EXPERIENCE_REGISTRY).filter((e) => e.family === family);
}

export function listProductExperiencesByStatus(
  status: StudioProductExperienceStatus
): StudioProductExperienceEntry[] {
  return Object.values(STUDIO_PRODUCT_EXPERIENCE_REGISTRY).filter((e) => e.status === status);
}

export function assertUniqueProductExperienceOwnership(): string[] {
  const seen = new Map<string, StudioProductExperienceId>();
  const dupes: string[] = [];
  for (const exp of Object.values(STUDIO_PRODUCT_EXPERIENCE_REGISTRY)) {
    for (const fan of exp.entryFans) {
      const key = fan.trim().toLowerCase();
      if (!key) continue;
      const prev = seen.get(key);
      if (prev && prev !== exp.experienceId) {
        dupes.push(`${key}:${prev}+${exp.experienceId}`);
      } else {
        seen.set(key, exp.experienceId);
      }
    }
  }
  return dupes;
}
